# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, CodeableReference, Identifier, Money, Period, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class AccountBalance(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    aggregate: CodeableConcept | None = Field(None, alias="aggregate", serialization_alias="aggregate")
    amount: Money = Field(alias="amount", serialization_alias="amount")
    estimate: bool | None = Field(None, alias="estimate", serialization_alias="estimate")
    term: CodeableConcept | None = Field(None, alias="term", serialization_alias="term")

class AccountCoverage(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    coverage: Reference = Field(alias="coverage", serialization_alias="coverage")
    priority: PositiveInt | None = Field(None, alias="priority", serialization_alias="priority")

class AccountDiagnosis(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    condition: CodeableReference = Field(alias="condition", serialization_alias="condition")
    date_of_diagnosis: str | None = Field(None, alias="dateOfDiagnosis", serialization_alias="dateOfDiagnosis")
    on_admission: bool | None = Field(None, alias="onAdmission", serialization_alias="onAdmission")
    package_code: PyList[CodeableConcept] | None = Field(None, alias="packageCode", serialization_alias="packageCode")
    sequence: PositiveInt | None = Field(None, alias="sequence", serialization_alias="sequence")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")

class AccountGuarantor(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    account: Reference | None = Field(None, alias="account", serialization_alias="account")
    on_hold: bool | None = Field(None, alias="onHold", serialization_alias="onHold")
    party: Reference | None = Field(None, alias="party", serialization_alias="party")
    period: Period | None = Field(None, alias="period", serialization_alias="period")

class AccountProcedure(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableReference = Field(alias="code", serialization_alias="code")
    date_of_service: str | None = Field(None, alias="dateOfService", serialization_alias="dateOfService")
    device: PyList[Reference] | None = Field(None, alias="device", serialization_alias="device")
    package_code: PyList[CodeableConcept] | None = Field(None, alias="packageCode", serialization_alias="packageCode")
    sequence: PositiveInt | None = Field(None, alias="sequence", serialization_alias="sequence")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")


class Account(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Account',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Account'
    )
    
    balance: PyList[AccountBalance] | None = Field(None, alias="balance", serialization_alias="balance")
    billing_status: CodeableConcept | None = Field(None, alias="billingStatus", serialization_alias="billingStatus")
    calculated_at: str | None = Field(None, alias="calculatedAt", serialization_alias="calculatedAt")
    coverage: PyList[AccountCoverage] | None = Field(None, alias="coverage", serialization_alias="coverage")
    covers: PyList[Reference] | None = Field(None, alias="covers", serialization_alias="covers")
    currency: CodeableConcept | None = Field(None, alias="currency", serialization_alias="currency")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    diagnosis: PyList[AccountDiagnosis] | None = Field(None, alias="diagnosis", serialization_alias="diagnosis")
    guarantor: PyList[AccountGuarantor] | None = Field(None, alias="guarantor", serialization_alias="guarantor")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    owner: Reference | None = Field(None, alias="owner", serialization_alias="owner")
    parent: Reference | None = Field(None, alias="parent", serialization_alias="parent")
    procedure: PyList[AccountProcedure] | None = Field(None, alias="procedure", serialization_alias="procedure")
    service_period: Period | None = Field(None, alias="servicePeriod", serialization_alias="servicePeriod")
    status: Literal["active", "inactive", "entered-in-error", "on-hold", "unknown"] = Field(alias="status", serialization_alias="status")
    subject: PyList[Reference] | None = Field(None, alias="subject", serialization_alias="subject")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Account:
        return cls.model_validate_json(json)

