# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, BackboneElement, CodeableConcept, CodeableReference, Identifier, Period, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class AdverseEventParticipant(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor: Reference = Field(alias="actor", serialization_alias="actor")
    function: CodeableConcept | None = Field(None, alias="function", serialization_alias="function")

class AdverseEventSuspectEntity(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    causality: AdverseEventSuspectEntityCausality | None = Field(None, alias="causality", serialization_alias="causality")
    instance: CodeableReference = Field(alias="instance", serialization_alias="instance")

class AdverseEventSuspectEntityCausality(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    assessment_method: CodeableConcept | None = Field(None, alias="assessmentMethod", serialization_alias="assessmentMethod")
    author: Reference | None = Field(None, alias="author", serialization_alias="author")
    entity_relatedness: CodeableConcept | None = Field(None, alias="entityRelatedness", serialization_alias="entityRelatedness")


class AdverseEvent(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='AdverseEvent',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='AdverseEvent'
    )
    
    actuality: Literal["actual", "potential"] = Field(alias="actuality", serialization_alias="actuality")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    cause_date_time: str | None = Field(None, alias="causeDateTime", serialization_alias="causeDateTime")
    cause_period: Period | None = Field(None, alias="causePeriod", serialization_alias="causePeriod")
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    contributing_factor: PyList[CodeableReference] | None = Field(None, alias="contributingFactor", serialization_alias="contributingFactor")
    detected: str | None = Field(None, alias="detected", serialization_alias="detected")
    effect_date_time: str | None = Field(None, alias="effectDateTime", serialization_alias="effectDateTime")
    effect_period: Period | None = Field(None, alias="effectPeriod", serialization_alias="effectPeriod")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    expected_in_research_study: bool | None = Field(None, alias="expectedInResearchStudy", serialization_alias="expectedInResearchStudy")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    location: Reference | None = Field(None, alias="location", serialization_alias="location")
    mitigating_action: PyList[CodeableReference] | None = Field(None, alias="mitigatingAction", serialization_alias="mitigatingAction")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    outcome: PyList[CodeableConcept] | None = Field(None, alias="outcome", serialization_alias="outcome")
    participant: PyList[AdverseEventParticipant] | None = Field(None, alias="participant", serialization_alias="participant")
    preventive_action: PyList[CodeableReference] | None = Field(None, alias="preventiveAction", serialization_alias="preventiveAction")
    recorded_date: str | None = Field(None, alias="recordedDate", serialization_alias="recordedDate")
    recorder: Reference | None = Field(None, alias="recorder", serialization_alias="recorder")
    resulting_effect: PyList[CodeableReference] | None = Field(None, alias="resultingEffect", serialization_alias="resultingEffect")
    seriousness: CodeableConcept | None = Field(None, alias="seriousness", serialization_alias="seriousness")
    status: Literal["in-progress", "completed", "entered-in-error", "unknown"] = Field(alias="status", serialization_alias="status")
    study: PyList[Reference] | None = Field(None, alias="study", serialization_alias="study")
    subject: Reference = Field(alias="subject", serialization_alias="subject")
    supporting_info: PyList[CodeableReference] | None = Field(None, alias="supportingInfo", serialization_alias="supportingInfo")
    suspect_entity: PyList[AdverseEventSuspectEntity] | None = Field(None, alias="suspectEntity", serialization_alias="suspectEntity")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> AdverseEvent:
        return cls.model_validate_json(json)

