# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Coding, Period, Quantity, Range, Ratio, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class AuditEventAgent(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    authorization: PyList[CodeableConcept] | None = Field(None, alias="authorization", serialization_alias="authorization")
    location: Reference | None = Field(None, alias="location", serialization_alias="location")
    network_reference: Reference | None = Field(None, alias="networkReference", serialization_alias="networkReference")
    network_string: str | None = Field(None, alias="networkString", serialization_alias="networkString")
    network_uri: str | None = Field(None, alias="networkUri", serialization_alias="networkUri")
    policy: PyList[str] | None = Field(None, alias="policy", serialization_alias="policy")
    requestor: bool | None = Field(None, alias="requestor", serialization_alias="requestor")
    role: PyList[CodeableConcept] | None = Field(None, alias="role", serialization_alias="role")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    who: Reference = Field(alias="who", serialization_alias="who")

class AuditEventEntity(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    agent: PyList[AuditEventAgent] | None = Field(None, alias="agent", serialization_alias="agent")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    detail: PyList[AuditEventEntityDetail] | None = Field(None, alias="detail", serialization_alias="detail")
    query: str | None = Field(None, alias="query", serialization_alias="query")
    role: CodeableConcept | None = Field(None, alias="role", serialization_alias="role")
    security_label: PyList[CodeableConcept] | None = Field(None, alias="securityLabel", serialization_alias="securityLabel")
    what: Reference | None = Field(None, alias="what", serialization_alias="what")

class AuditEventEntityDetail(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    value_base64binary: str | None = Field(None, alias="valueBase64Binary", serialization_alias="valueBase64Binary")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_date_time: str | None = Field(None, alias="valueDateTime", serialization_alias="valueDateTime")
    value_integer: int | None = Field(None, alias="valueInteger", serialization_alias="valueInteger")
    value_period: Period | None = Field(None, alias="valuePeriod", serialization_alias="valuePeriod")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_range: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")
    value_ratio: Ratio | None = Field(None, alias="valueRatio", serialization_alias="valueRatio")
    value_string: str | None = Field(None, alias="valueString", serialization_alias="valueString")
    value_time: str | None = Field(None, alias="valueTime", serialization_alias="valueTime")

class AuditEventOutcome(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: Coding = Field(alias="code", serialization_alias="code")
    detail: PyList[CodeableConcept] | None = Field(None, alias="detail", serialization_alias="detail")

class AuditEventSource(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    observer: Reference = Field(alias="observer", serialization_alias="observer")
    site: Reference | None = Field(None, alias="site", serialization_alias="site")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")


class AuditEvent(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='AuditEvent',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='AuditEvent'
    )
    
    action: Literal["C", "R", "U", "D", "E"] | None = Field(None, alias="action", serialization_alias="action")
    agent: PyList[AuditEventAgent] = Field(alias="agent", serialization_alias="agent")
    authorization: PyList[CodeableConcept] | None = Field(None, alias="authorization", serialization_alias="authorization")
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    entity: PyList[AuditEventEntity] | None = Field(None, alias="entity", serialization_alias="entity")
    occurred_date_time: str | None = Field(None, alias="occurredDateTime", serialization_alias="occurredDateTime")
    occurred_period: Period | None = Field(None, alias="occurredPeriod", serialization_alias="occurredPeriod")
    outcome: AuditEventOutcome | None = Field(None, alias="outcome", serialization_alias="outcome")
    patient: Reference | None = Field(None, alias="patient", serialization_alias="patient")
    recorded: str = Field(alias="recorded", serialization_alias="recorded")
    severity: Literal["emergency", "alert", "critical", "error", "warning", "notice", "informational", "debug"] | None = Field(None, alias="severity", serialization_alias="severity")
    source: AuditEventSource = Field(alias="source", serialization_alias="source")
    subtype: PyList[CodeableConcept] | None = Field(None, alias="subtype", serialization_alias="subtype")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> AuditEvent:
        return cls.model_validate_json(json)

