# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Attachment, BackboneElement, CodeableConcept, CodeableReference, Identifier, Quantity, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class BodyStructureIncludedStructure(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    body_landmark_orientation: PyList[BodyStructureIncludedStructureBodyLandmarkOrientation] | None = Field(None, alias="bodyLandmarkOrientation", serialization_alias="bodyLandmarkOrientation")
    laterality: CodeableConcept | None = Field(None, alias="laterality", serialization_alias="laterality")
    qualifier: PyList[CodeableConcept] | None = Field(None, alias="qualifier", serialization_alias="qualifier")
    spatial_reference: PyList[Reference] | None = Field(None, alias="spatialReference", serialization_alias="spatialReference")
    structure: CodeableConcept = Field(alias="structure", serialization_alias="structure")

class BodyStructureIncludedStructureBodyLandmarkOrientation(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    clock_face_position: PyList[CodeableConcept] | None = Field(None, alias="clockFacePosition", serialization_alias="clockFacePosition")
    distance_from_landmark: PyList[BodyStructureIncludedStructureBodyLandmarkOrientationDistanceFromLandmark] | None = Field(None, alias="distanceFromLandmark", serialization_alias="distanceFromLandmark")
    landmark_description: PyList[CodeableConcept] | None = Field(None, alias="landmarkDescription", serialization_alias="landmarkDescription")
    surface_orientation: PyList[CodeableConcept] | None = Field(None, alias="surfaceOrientation", serialization_alias="surfaceOrientation")

class BodyStructureIncludedStructureBodyLandmarkOrientationDistanceFromLandmark(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    device: PyList[CodeableReference] | None = Field(None, alias="device", serialization_alias="device")
    value: PyList[Quantity] | None = Field(None, alias="value", serialization_alias="value")


class BodyStructure(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='BodyStructure',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='BodyStructure'
    )
    
    active: bool | None = Field(None, alias="active", serialization_alias="active")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    excluded_structure: PyList[BodyStructureIncludedStructure] | None = Field(None, alias="excludedStructure", serialization_alias="excludedStructure")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    image: PyList[Attachment] | None = Field(None, alias="image", serialization_alias="image")
    included_structure: PyList[BodyStructureIncludedStructure] = Field(alias="includedStructure", serialization_alias="includedStructure")
    morphology: CodeableConcept | None = Field(None, alias="morphology", serialization_alias="morphology")
    patient: Reference = Field(alias="patient", serialization_alias="patient")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> BodyStructure:
        return cls.model_validate_json(json)

