# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Coding, ContactDetail, Expression, Identifier, MonetaryComponent, Period, \
    Reference, RelatedArtifact, UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ChargeItemDefinitionApplicability(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    condition: Expression | None = Field(None, alias="condition", serialization_alias="condition")
    effective_period: Period | None = Field(None, alias="effectivePeriod", serialization_alias="effectivePeriod")
    related_artifact: RelatedArtifact | None = Field(None, alias="relatedArtifact", serialization_alias="relatedArtifact")

class ChargeItemDefinitionPropertyGroup(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    applicability: PyList[ChargeItemDefinitionApplicability] | None = Field(None, alias="applicability", serialization_alias="applicability")
    price_component: PyList[MonetaryComponent] | None = Field(None, alias="priceComponent", serialization_alias="priceComponent")


class ChargeItemDefinition(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ChargeItemDefinition',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ChargeItemDefinition'
    )
    
    account: PyList[Reference] | None = Field(None, alias="account", serialization_alias="account")
    applicability: PyList[ChargeItemDefinitionApplicability] | None = Field(None, alias="applicability", serialization_alias="applicability")
    approval_date: str | None = Field(None, alias="approvalDate", serialization_alias="approvalDate")
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    derived_from_uri: PyList[str] | None = Field(None, alias="derivedFromUri", serialization_alias="derivedFromUri")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    instance: PyList[Reference] | None = Field(None, alias="instance", serialization_alias="instance")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    last_review_date: str | None = Field(None, alias="lastReviewDate", serialization_alias="lastReviewDate")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    part_of: PyList[str] | None = Field(None, alias="partOf", serialization_alias="partOf")
    property_group: PyList[ChargeItemDefinitionPropertyGroup] | None = Field(None, alias="propertyGroup", serialization_alias="propertyGroup")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    replaces: PyList[str] | None = Field(None, alias="replaces", serialization_alias="replaces")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ChargeItemDefinition:
        return cls.model_validate_json(json)

