# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, Attachment, BackboneElement, CodeableConcept, Coding, ContactDetail, Identifier, Period, Reference, \
    UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class CitationCitedArtifact(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    abstract: PyList[CitationCitedArtifactAbstract] | None = Field(None, alias="abstract", serialization_alias="abstract")
    base_citation: Reference | None = Field(None, alias="baseCitation", serialization_alias="baseCitation")
    classification: PyList[CitationCitedArtifactClassification] | None = Field(None, alias="classification", serialization_alias="classification")
    contributorship: CitationCitedArtifactContributorship | None = Field(None, alias="contributorship", serialization_alias="contributorship")
    current_state: PyList[CodeableConcept] | None = Field(None, alias="currentState", serialization_alias="currentState")
    date_accessed: str | None = Field(None, alias="dateAccessed", serialization_alias="dateAccessed")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    part: CitationCitedArtifactPart | None = Field(None, alias="part", serialization_alias="part")
    publication_form: PyList[CitationCitedArtifactPublicationForm] | None = Field(None, alias="publicationForm", serialization_alias="publicationForm")
    related_identifier: PyList[Identifier] | None = Field(None, alias="relatedIdentifier", serialization_alias="relatedIdentifier")
    relates_to: PyList[CitationCitedArtifactRelatesTo] | None = Field(None, alias="relatesTo", serialization_alias="relatesTo")
    status_date: PyList[CitationCitedArtifactStatusDate] | None = Field(None, alias="statusDate", serialization_alias="statusDate")
    title: PyList[CitationCitedArtifactTitle] | None = Field(None, alias="title", serialization_alias="title")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    web_location: PyList[CitationCitedArtifactWebLocation] | None = Field(None, alias="webLocation", serialization_alias="webLocation")

class CitationCitedArtifactAbstract(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    language: str | None = Field(None, alias="language", serialization_alias="language")
    text: str = Field(alias="text", serialization_alias="text")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")

class CitationCitedArtifactClassification(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    artifact_assessment: PyList[Reference] | None = Field(None, alias="artifactAssessment", serialization_alias="artifactAssessment")
    classifier: PyList[CodeableConcept] | None = Field(None, alias="classifier", serialization_alias="classifier")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class CitationCitedArtifactContributorship(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    complete: bool | None = Field(None, alias="complete", serialization_alias="complete")
    entry: PyList[CitationCitedArtifactContributorshipEntry] | None = Field(None, alias="entry", serialization_alias="entry")
    summary: PyList[CitationCitedArtifactContributorshipSummary] | None = Field(None, alias="summary", serialization_alias="summary")

class CitationCitedArtifactContributorshipEntry(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    affiliation: PyList[Reference] | None = Field(None, alias="affiliation", serialization_alias="affiliation")
    contribution_instance: PyList[CitationCitedArtifactContributorshipEntryContributionInstance] | None = Field(None, alias="contributionInstance", serialization_alias="contributionInstance")
    contribution_type: PyList[CodeableConcept] | None = Field(None, alias="contributionType", serialization_alias="contributionType")
    contributor: Reference = Field(alias="contributor", serialization_alias="contributor")
    corresponding_contact: bool | None = Field(None, alias="correspondingContact", serialization_alias="correspondingContact")
    forename_initials: str | None = Field(None, alias="forenameInitials", serialization_alias="forenameInitials")
    ranking_order: PositiveInt | None = Field(None, alias="rankingOrder", serialization_alias="rankingOrder")
    role: CodeableConcept | None = Field(None, alias="role", serialization_alias="role")

class CitationCitedArtifactContributorshipEntryContributionInstance(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    time: str | None = Field(None, alias="time", serialization_alias="time")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class CitationCitedArtifactContributorshipSummary(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    source: CodeableConcept | None = Field(None, alias="source", serialization_alias="source")
    style: PyList[CodeableConcept] | None = Field(None, alias="style", serialization_alias="style")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    value: str = Field(alias="value", serialization_alias="value")

class CitationCitedArtifactPart(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    value: str | None = Field(None, alias="value", serialization_alias="value")

class CitationCitedArtifactPublicationForm(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    accession_number: str | None = Field(None, alias="accessionNumber", serialization_alias="accessionNumber")
    article_date: str | None = Field(None, alias="articleDate", serialization_alias="articleDate")
    cited_medium: CodeableConcept | None = Field(None, alias="citedMedium", serialization_alias="citedMedium")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    first_page: str | None = Field(None, alias="firstPage", serialization_alias="firstPage")
    issue: str | None = Field(None, alias="issue", serialization_alias="issue")
    language: PyList[str] | None = Field(None, alias="language", serialization_alias="language")
    last_page: str | None = Field(None, alias="lastPage", serialization_alias="lastPage")
    last_revision_date: str | None = Field(None, alias="lastRevisionDate", serialization_alias="lastRevisionDate")
    page_count: str | None = Field(None, alias="pageCount", serialization_alias="pageCount")
    page_string: str | None = Field(None, alias="pageString", serialization_alias="pageString")
    publication_date_season: str | None = Field(None, alias="publicationDateSeason", serialization_alias="publicationDateSeason")
    publication_date_text: str | None = Field(None, alias="publicationDateText", serialization_alias="publicationDateText")
    published_in: CitationCitedArtifactPublicationFormPublishedIn | None = Field(None, alias="publishedIn", serialization_alias="publishedIn")
    volume: str | None = Field(None, alias="volume", serialization_alias="volume")

class CitationCitedArtifactPublicationFormPublishedIn(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    publisher: Reference | None = Field(None, alias="publisher", serialization_alias="publisher")
    publisher_location: str | None = Field(None, alias="publisherLocation", serialization_alias="publisherLocation")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class CitationCitedArtifactRelatesTo(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    citation: str | None = Field(None, alias="citation", serialization_alias="citation")
    classifier: PyList[CodeableConcept] | None = Field(None, alias="classifier", serialization_alias="classifier")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    label: str | None = Field(None, alias="label", serialization_alias="label")
    target_attachment: Attachment | None = Field(None, alias="targetAttachment", serialization_alias="targetAttachment")
    target_canonical: str | None = Field(None, alias="targetCanonical", serialization_alias="targetCanonical")
    target_reference: Reference | None = Field(None, alias="targetReference", serialization_alias="targetReference")
    target_uri: str | None = Field(None, alias="targetUri", serialization_alias="targetUri")
    type: Literal["documentation", "justification", "predecessor", "successor", "derived-from", "depends-on", "composed-of", "part-of", "amends", "amended-with", "appends", "appended-with", "cites", "cited-by", "comments-on", "comment-in", "contains", "contained-in", "corrects", "correction-in", "replaces", "replaced-with", "retracts", "retracted-by", "signs", "similar-to", "supports", "supported-with", "transforms", "transformed-into", "transformed-with", "specification-of", "created-with", "cite-as", "summarizes"] = Field(alias="type", serialization_alias="type")

class CitationCitedArtifactStatusDate(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    activity: CodeableConcept = Field(alias="activity", serialization_alias="activity")
    actual: bool | None = Field(None, alias="actual", serialization_alias="actual")
    period: Period = Field(alias="period", serialization_alias="period")

class CitationCitedArtifactTitle(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    language: str | None = Field(None, alias="language", serialization_alias="language")
    text: str = Field(alias="text", serialization_alias="text")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")

class CitationCitedArtifactWebLocation(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    classifier: PyList[CodeableConcept] | None = Field(None, alias="classifier", serialization_alias="classifier")
    url: str | None = Field(None, alias="url", serialization_alias="url")

class CitationClassification(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    classifier: PyList[CodeableConcept] | None = Field(None, alias="classifier", serialization_alias="classifier")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class CitationRelatesTo(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    target_attachment: Attachment | None = Field(None, alias="targetAttachment", serialization_alias="targetAttachment")
    target_canonical: str | None = Field(None, alias="targetCanonical", serialization_alias="targetCanonical")
    target_markdown: str | None = Field(None, alias="targetMarkdown", serialization_alias="targetMarkdown")
    target_reference: Reference | None = Field(None, alias="targetReference", serialization_alias="targetReference")
    target_uri: str | None = Field(None, alias="targetUri", serialization_alias="targetUri")
    type: Literal["documentation", "justification", "predecessor", "successor", "derived-from", "depends-on", "composed-of", "part-of", "amends", "amended-with", "appends", "appended-with", "cites", "cited-by", "comments-on", "comment-in", "contains", "contained-in", "corrects", "correction-in", "replaces", "replaced-with", "retracts", "retracted-by", "signs", "similar-to", "supports", "supported-with", "transforms", "transformed-into", "transformed-with", "specification-of", "created-with", "cite-as", "summarizes"] = Field(alias="type", serialization_alias="type")

class CitationStatusDate(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    activity: CodeableConcept = Field(alias="activity", serialization_alias="activity")
    actual: bool | None = Field(None, alias="actual", serialization_alias="actual")
    period: Period = Field(alias="period", serialization_alias="period")

class CitationSummary(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    style: CodeableConcept | None = Field(None, alias="style", serialization_alias="style")
    text: str = Field(alias="text", serialization_alias="text")


class Citation(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Citation',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Citation'
    )
    
    approval_date: str | None = Field(None, alias="approvalDate", serialization_alias="approvalDate")
    author: PyList[ContactDetail] | None = Field(None, alias="author", serialization_alias="author")
    cited_artifact: CitationCitedArtifact | None = Field(None, alias="citedArtifact", serialization_alias="citedArtifact")
    classification: PyList[CitationClassification] | None = Field(None, alias="classification", serialization_alias="classification")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    current_state: PyList[CodeableConcept] | None = Field(None, alias="currentState", serialization_alias="currentState")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    editor: PyList[ContactDetail] | None = Field(None, alias="editor", serialization_alias="editor")
    effective_period: Period | None = Field(None, alias="effectivePeriod", serialization_alias="effectivePeriod")
    endorser: PyList[ContactDetail] | None = Field(None, alias="endorser", serialization_alias="endorser")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    last_review_date: str | None = Field(None, alias="lastReviewDate", serialization_alias="lastReviewDate")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    recorder: PyList[ContactDetail] | None = Field(None, alias="recorder", serialization_alias="recorder")
    relates_to: PyList[CitationRelatesTo] | None = Field(None, alias="relatesTo", serialization_alias="relatesTo")
    reviewer: PyList[ContactDetail] | None = Field(None, alias="reviewer", serialization_alias="reviewer")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    status_date: PyList[CitationStatusDate] | None = Field(None, alias="statusDate", serialization_alias="statusDate")
    summary: PyList[CitationSummary] | None = Field(None, alias="summary", serialization_alias="summary")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Citation:
        return cls.model_validate_json(json)

