# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, CodeableReference, Expression, Identifier, Range, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ClinicalUseDefinitionContraindication(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    applicability: Expression | None = Field(None, alias="applicability", serialization_alias="applicability")
    comorbidity: PyList[CodeableReference] | None = Field(None, alias="comorbidity", serialization_alias="comorbidity")
    disease_status: CodeableReference | None = Field(None, alias="diseaseStatus", serialization_alias="diseaseStatus")
    disease_symptom_procedure: CodeableReference | None = Field(None, alias="diseaseSymptomProcedure", serialization_alias="diseaseSymptomProcedure")
    indication: PyList[Reference] | None = Field(None, alias="indication", serialization_alias="indication")
    other_therapy: PyList[ClinicalUseDefinitionContraindicationOtherTherapy] | None = Field(None, alias="otherTherapy", serialization_alias="otherTherapy")

class ClinicalUseDefinitionContraindicationOtherTherapy(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    relationship_type: CodeableConcept = Field(alias="relationshipType", serialization_alias="relationshipType")
    treatment: CodeableReference = Field(alias="treatment", serialization_alias="treatment")

class ClinicalUseDefinitionIndication(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    applicability: Expression | None = Field(None, alias="applicability", serialization_alias="applicability")
    comorbidity: PyList[CodeableReference] | None = Field(None, alias="comorbidity", serialization_alias="comorbidity")
    disease_status: CodeableReference | None = Field(None, alias="diseaseStatus", serialization_alias="diseaseStatus")
    disease_symptom_procedure: CodeableReference | None = Field(None, alias="diseaseSymptomProcedure", serialization_alias="diseaseSymptomProcedure")
    duration_range: Range | None = Field(None, alias="durationRange", serialization_alias="durationRange")
    duration_string: str | None = Field(None, alias="durationString", serialization_alias="durationString")
    intended_effect: CodeableReference | None = Field(None, alias="intendedEffect", serialization_alias="intendedEffect")
    other_therapy: PyList[ClinicalUseDefinitionContraindicationOtherTherapy] | None = Field(None, alias="otherTherapy", serialization_alias="otherTherapy")
    undesirable_effect: PyList[Reference] | None = Field(None, alias="undesirableEffect", serialization_alias="undesirableEffect")

class ClinicalUseDefinitionInteraction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    effect: CodeableReference | None = Field(None, alias="effect", serialization_alias="effect")
    incidence: CodeableConcept | None = Field(None, alias="incidence", serialization_alias="incidence")
    interactant: PyList[ClinicalUseDefinitionInteractionInteractant] | None = Field(None, alias="interactant", serialization_alias="interactant")
    management: PyList[CodeableConcept] | None = Field(None, alias="management", serialization_alias="management")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class ClinicalUseDefinitionInteractionInteractant(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    item_codeable_concept: CodeableConcept | None = Field(None, alias="itemCodeableConcept", serialization_alias="itemCodeableConcept")
    item_reference: Reference | None = Field(None, alias="itemReference", serialization_alias="itemReference")

class ClinicalUseDefinitionUndesirableEffect(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    classification: CodeableConcept | None = Field(None, alias="classification", serialization_alias="classification")
    frequency_of_occurrence: CodeableConcept | None = Field(None, alias="frequencyOfOccurrence", serialization_alias="frequencyOfOccurrence")
    symptom_condition_effect: CodeableReference | None = Field(None, alias="symptomConditionEffect", serialization_alias="symptomConditionEffect")

class ClinicalUseDefinitionWarning(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    description: str | None = Field(None, alias="description", serialization_alias="description")


class ClinicalUseDefinition(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ClinicalUseDefinition',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ClinicalUseDefinition'
    )
    
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    contraindication: ClinicalUseDefinitionContraindication | None = Field(None, alias="contraindication", serialization_alias="contraindication")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    indication: ClinicalUseDefinitionIndication | None = Field(None, alias="indication", serialization_alias="indication")
    interaction: ClinicalUseDefinitionInteraction | None = Field(None, alias="interaction", serialization_alias="interaction")
    library: PyList[str] | None = Field(None, alias="library", serialization_alias="library")
    population: PyList[Reference] | None = Field(None, alias="population", serialization_alias="population")
    status: CodeableConcept | None = Field(None, alias="status", serialization_alias="status")
    subject: PyList[Reference] | None = Field(None, alias="subject", serialization_alias="subject")
    type: Literal["indication", "contraindication", "interaction", "undesirable-effect", "warning"] = Field(alias="type", serialization_alias="type")
    undesirable_effect: ClinicalUseDefinitionUndesirableEffect | None = Field(None, alias="undesirableEffect", serialization_alias="undesirableEffect")
    warning: ClinicalUseDefinitionWarning | None = Field(None, alias="warning", serialization_alias="warning")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ClinicalUseDefinition:
        return cls.model_validate_json(json)

