# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, Attachment, BackboneElement, CodeableConcept, CodeableReference, Identifier, Narrative, Period, \
    Reference, UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class CompositionAttester(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    mode: CodeableConcept = Field(alias="mode", serialization_alias="mode")
    party: Reference | None = Field(None, alias="party", serialization_alias="party")
    time: str | None = Field(None, alias="time", serialization_alias="time")

class CompositionEvent(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    detail: PyList[CodeableReference] | None = Field(None, alias="detail", serialization_alias="detail")
    period: Period | None = Field(None, alias="period", serialization_alias="period")

class CompositionRelatesTo(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    target_attachment: Attachment | None = Field(None, alias="targetAttachment", serialization_alias="targetAttachment")
    target_canonical: str | None = Field(None, alias="targetCanonical", serialization_alias="targetCanonical")
    target_markdown: str | None = Field(None, alias="targetMarkdown", serialization_alias="targetMarkdown")
    target_reference: Reference | None = Field(None, alias="targetReference", serialization_alias="targetReference")
    target_uri: str | None = Field(None, alias="targetUri", serialization_alias="targetUri")
    type: Literal["documentation", "justification", "predecessor", "successor", "derived-from", "depends-on", "composed-of", "part-of", "amends", "amended-with", "appends", "appended-with", "cites", "cited-by", "comments-on", "comment-in", "contains", "contained-in", "corrects", "correction-in", "replaces", "replaced-with", "retracts", "retracted-by", "signs", "similar-to", "supports", "supported-with", "transforms", "transformed-into", "transformed-with", "specification-of", "created-with", "cite-as", "summarizes"] = Field(alias="type", serialization_alias="type")

class CompositionSection(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    author: PyList[Reference] | None = Field(None, alias="author", serialization_alias="author")
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    empty_reason: CodeableConcept | None = Field(None, alias="emptyReason", serialization_alias="emptyReason")
    entry: PyList[Reference] | None = Field(None, alias="entry", serialization_alias="entry")
    focus: Reference | None = Field(None, alias="focus", serialization_alias="focus")
    ordered_by: CodeableConcept | None = Field(None, alias="orderedBy", serialization_alias="orderedBy")
    section: PyList[CompositionSection] | None = Field(None, alias="section", serialization_alias="section")
    text: Narrative | None = Field(None, alias="text", serialization_alias="text")
    title: str | None = Field(None, alias="title", serialization_alias="title")


class Composition(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Composition',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Composition'
    )
    
    attester: PyList[CompositionAttester] | None = Field(None, alias="attester", serialization_alias="attester")
    author: PyList[Reference] = Field(alias="author", serialization_alias="author")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    custodian: Reference | None = Field(None, alias="custodian", serialization_alias="custodian")
    date: str = Field(alias="date", serialization_alias="date")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    event: PyList[CompositionEvent] | None = Field(None, alias="event", serialization_alias="event")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    relates_to: PyList[CompositionRelatesTo] | None = Field(None, alias="relatesTo", serialization_alias="relatesTo")
    section: PyList[CompositionSection] | None = Field(None, alias="section", serialization_alias="section")
    status: Literal["registered", "partial", "final", "amended", "cancelled", "entered-in-error", "deprecated", "unknown", "preliminary", "corrected", "appended"] = Field(alias="status", serialization_alias="status")
    subject: PyList[Reference] | None = Field(None, alias="subject", serialization_alias="subject")
    title: str = Field(alias="title", serialization_alias="title")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Composition:
        return cls.model_validate_json(json)

