# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Coding, ContactDetail, Identifier, Period, Quantity, RelatedArtifact, \
    UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ConceptMapAdditionalAttribute(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: str = Field(alias="code", serialization_alias="code")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    type: Literal["code", "Coding", "string", "boolean", "Quantity"] = Field(alias="type", serialization_alias="type")
    uri: str | None = Field(None, alias="uri", serialization_alias="uri")

class ConceptMapGroup(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    element: PyList[ConceptMapGroupElement] = Field(alias="element", serialization_alias="element")
    source: str | None = Field(None, alias="source", serialization_alias="source")
    target: str | None = Field(None, alias="target", serialization_alias="target")
    unmapped: ConceptMapGroupUnmapped | None = Field(None, alias="unmapped", serialization_alias="unmapped")

class ConceptMapGroupElement(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: str | None = Field(None, alias="code", serialization_alias="code")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    no_map: bool | None = Field(None, alias="noMap", serialization_alias="noMap")
    target: PyList[ConceptMapGroupElementTarget] | None = Field(None, alias="target", serialization_alias="target")
    value_set: str | None = Field(None, alias="valueSet", serialization_alias="valueSet")

class ConceptMapGroupElementTarget(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: str | None = Field(None, alias="code", serialization_alias="code")
    comment: str | None = Field(None, alias="comment", serialization_alias="comment")
    depends_on: PyList[ConceptMapGroupElementTargetDependsOn] | None = Field(None, alias="dependsOn", serialization_alias="dependsOn")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    product: PyList[ConceptMapGroupElementTargetDependsOn] | None = Field(None, alias="product", serialization_alias="product")
    property: PyList[ConceptMapGroupElementTargetProperty] | None = Field(None, alias="property", serialization_alias="property")
    relationship: Literal["related-to", "not-related-to", "equivalent", "source-is-narrower-than-target", "source-is-broader-than-target"] = Field(alias="relationship", serialization_alias="relationship")
    value_set: str | None = Field(None, alias="valueSet", serialization_alias="valueSet")

class ConceptMapGroupElementTargetDependsOn(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    attribute: str = Field(alias="attribute", serialization_alias="attribute")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_code: str | None = Field(None, alias="valueCode", serialization_alias="valueCode")
    value_coding: Coding | None = Field(None, alias="valueCoding", serialization_alias="valueCoding")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_set: str | None = Field(None, alias="valueSet", serialization_alias="valueSet")
    value_string: str | None = Field(None, alias="valueString", serialization_alias="valueString")

class ConceptMapGroupElementTargetProperty(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: str = Field(alias="code", serialization_alias="code")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_code: str | None = Field(None, alias="valueCode", serialization_alias="valueCode")
    value_coding: Coding | None = Field(None, alias="valueCoding", serialization_alias="valueCoding")
    value_date_time: str | None = Field(None, alias="valueDateTime", serialization_alias="valueDateTime")
    value_decimal: float | None = Field(None, alias="valueDecimal", serialization_alias="valueDecimal")
    value_integer: int | None = Field(None, alias="valueInteger", serialization_alias="valueInteger")
    value_string: str | None = Field(None, alias="valueString", serialization_alias="valueString")

class ConceptMapGroupUnmapped(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: str | None = Field(None, alias="code", serialization_alias="code")
    display: str | None = Field(None, alias="display", serialization_alias="display")
    mode: Literal["use-source-code", "fixed", "other-map"] = Field(alias="mode", serialization_alias="mode")
    other_map: str | None = Field(None, alias="otherMap", serialization_alias="otherMap")
    relationship: Literal["related-to", "not-related-to", "equivalent", "source-is-narrower-than-target", "source-is-broader-than-target"] | None = Field(None, alias="relationship", serialization_alias="relationship")
    value_set: str | None = Field(None, alias="valueSet", serialization_alias="valueSet")

class ConceptMapProperty(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: str = Field(alias="code", serialization_alias="code")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    system: str | None = Field(None, alias="system", serialization_alias="system")
    type: Literal["Coding", "string", "integer", "boolean", "dateTime", "decimal", "code"] = Field(alias="type", serialization_alias="type")
    uri: str | None = Field(None, alias="uri", serialization_alias="uri")


class ConceptMap(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ConceptMap',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ConceptMap'
    )
    
    additional_attribute: PyList[ConceptMapAdditionalAttribute] | None = Field(None, alias="additionalAttribute", serialization_alias="additionalAttribute")
    approval_date: str | None = Field(None, alias="approvalDate", serialization_alias="approvalDate")
    author: PyList[ContactDetail] | None = Field(None, alias="author", serialization_alias="author")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    editor: PyList[ContactDetail] | None = Field(None, alias="editor", serialization_alias="editor")
    effective_period: Period | None = Field(None, alias="effectivePeriod", serialization_alias="effectivePeriod")
    endorser: PyList[ContactDetail] | None = Field(None, alias="endorser", serialization_alias="endorser")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    group: PyList[ConceptMapGroup] | None = Field(None, alias="group", serialization_alias="group")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    last_review_date: str | None = Field(None, alias="lastReviewDate", serialization_alias="lastReviewDate")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    property: PyList[ConceptMapProperty] | None = Field(None, alias="property", serialization_alias="property")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    related_artifact: PyList[RelatedArtifact] | None = Field(None, alias="relatedArtifact", serialization_alias="relatedArtifact")
    reviewer: PyList[ContactDetail] | None = Field(None, alias="reviewer", serialization_alias="reviewer")
    source_scope_canonical: str | None = Field(None, alias="sourceScopeCanonical", serialization_alias="sourceScopeCanonical")
    source_scope_uri: str | None = Field(None, alias="sourceScopeUri", serialization_alias="sourceScopeUri")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    target_scope_canonical: str | None = Field(None, alias="targetScopeCanonical", serialization_alias="targetScopeCanonical")
    target_scope_uri: str | None = Field(None, alias="targetScopeUri", serialization_alias="targetScopeUri")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    topic: PyList[CodeableConcept] | None = Field(None, alias="topic", serialization_alias="topic")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ConceptMap:
        return cls.model_validate_json(json)

