# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Coding, ContactDetail, Identifier, Quantity, Reference, UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ConditionDefinitionMedication(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    category: CodeableConcept | None = Field(None, alias="category", serialization_alias="category")
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")

class ConditionDefinitionPlan(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    reference: Reference = Field(alias="reference", serialization_alias="reference")
    role: CodeableConcept | None = Field(None, alias="role", serialization_alias="role")

class ConditionDefinitionPrecondition(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    type: Literal["sensitive", "specific"] = Field(alias="type", serialization_alias="type")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")

class ConditionDefinitionQuestionnaire(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    purpose: Literal["preadmit", "diff-diagnosis", "outcome"] = Field(alias="purpose", serialization_alias="purpose")
    reference: Reference = Field(alias="reference", serialization_alias="reference")


class ConditionDefinition(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ConditionDefinition',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ConditionDefinition'
    )
    
    body_site: CodeableConcept | None = Field(None, alias="bodySite", serialization_alias="bodySite")
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    definition: PyList[str] | None = Field(None, alias="definition", serialization_alias="definition")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    has_body_site: bool | None = Field(None, alias="hasBodySite", serialization_alias="hasBodySite")
    has_severity: bool | None = Field(None, alias="hasSeverity", serialization_alias="hasSeverity")
    has_stage: bool | None = Field(None, alias="hasStage", serialization_alias="hasStage")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    medication: PyList[ConditionDefinitionMedication] | None = Field(None, alias="medication", serialization_alias="medication")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    observation: PyList[str] | None = Field(None, alias="observation", serialization_alias="observation")
    plan: PyList[ConditionDefinitionPlan] | None = Field(None, alias="plan", serialization_alias="plan")
    precondition: PyList[ConditionDefinitionPrecondition] | None = Field(None, alias="precondition", serialization_alias="precondition")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    questionnaire: PyList[ConditionDefinitionQuestionnaire] | None = Field(None, alias="questionnaire", serialization_alias="questionnaire")
    severity: CodeableConcept | None = Field(None, alias="severity", serialization_alias="severity")
    stage: CodeableConcept | None = Field(None, alias="stage", serialization_alias="stage")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    subtitle: str | None = Field(None, alias="subtitle", serialization_alias="subtitle")
    team: PyList[Reference] | None = Field(None, alias="team", serialization_alias="team")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ConditionDefinition:
        return cls.model_validate_json(json)

