# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Attachment, BackboneElement, CodeableConcept, Coding, Expression, Identifier, Period, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ConsentPolicyBasis(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    reference: Reference | None = Field(None, alias="reference", serialization_alias="reference")
    uri: str | None = Field(None, alias="uri", serialization_alias="uri")

class ConsentProvision(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: PyList[CodeableConcept] | None = Field(None, alias="action", serialization_alias="action")
    actor: PyList[ConsentProvisionActor] | None = Field(None, alias="actor", serialization_alias="actor")
    code: PyList[CodeableConcept] | None = Field(None, alias="code", serialization_alias="code")
    data: PyList[ConsentProvisionData] | None = Field(None, alias="data", serialization_alias="data")
    data_period: Period | None = Field(None, alias="dataPeriod", serialization_alias="dataPeriod")
    document_type: PyList[Coding] | None = Field(None, alias="documentType", serialization_alias="documentType")
    expression: Expression | None = Field(None, alias="expression", serialization_alias="expression")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    provision: PyList[ConsentProvision] | None = Field(None, alias="provision", serialization_alias="provision")
    purpose: PyList[Coding] | None = Field(None, alias="purpose", serialization_alias="purpose")
    resource_type: PyList[Coding] | None = Field(None, alias="resourceType", serialization_alias="resourceType")
    security_label: PyList[Coding] | None = Field(None, alias="securityLabel", serialization_alias="securityLabel")

class ConsentProvisionActor(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    reference: Reference | None = Field(None, alias="reference", serialization_alias="reference")
    role: CodeableConcept | None = Field(None, alias="role", serialization_alias="role")

class ConsentProvisionData(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    meaning: Literal["instance", "related", "dependents", "authoredby"] = Field(alias="meaning", serialization_alias="meaning")
    reference: Reference = Field(alias="reference", serialization_alias="reference")

class ConsentVerification(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    verification_date: PyList[str] | None = Field(None, alias="verificationDate", serialization_alias="verificationDate")
    verification_type: CodeableConcept | None = Field(None, alias="verificationType", serialization_alias="verificationType")
    verified: bool = Field(alias="verified", serialization_alias="verified")
    verified_by: Reference | None = Field(None, alias="verifiedBy", serialization_alias="verifiedBy")
    verified_with: Reference | None = Field(None, alias="verifiedWith", serialization_alias="verifiedWith")


class Consent(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Consent',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Consent'
    )
    
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    controller: PyList[Reference] | None = Field(None, alias="controller", serialization_alias="controller")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    decision: Literal["deny", "permit"] | None = Field(None, alias="decision", serialization_alias="decision")
    grantee: PyList[Reference] | None = Field(None, alias="grantee", serialization_alias="grantee")
    grantor: PyList[Reference] | None = Field(None, alias="grantor", serialization_alias="grantor")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    manager: PyList[Reference] | None = Field(None, alias="manager", serialization_alias="manager")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    policy_basis: ConsentPolicyBasis | None = Field(None, alias="policyBasis", serialization_alias="policyBasis")
    policy_text: PyList[Reference] | None = Field(None, alias="policyText", serialization_alias="policyText")
    provision: PyList[ConsentProvision] | None = Field(None, alias="provision", serialization_alias="provision")
    provision_reference: PyList[Reference] | None = Field(None, alias="provisionReference", serialization_alias="provisionReference")
    regulatory_basis: PyList[CodeableConcept] | None = Field(None, alias="regulatoryBasis", serialization_alias="regulatoryBasis")
    source_attachment: PyList[Attachment] | None = Field(None, alias="sourceAttachment", serialization_alias="sourceAttachment")
    source_reference: PyList[Reference] | None = Field(None, alias="sourceReference", serialization_alias="sourceReference")
    status: Literal["draft", "active", "inactive", "not-done", "entered-in-error", "unknown"] = Field(alias="status", serialization_alias="status")
    subject: Reference | None = Field(None, alias="subject", serialization_alias="subject")
    verification: PyList[ConsentVerification] | None = Field(None, alias="verification", serialization_alias="verification")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Consent:
        return cls.model_validate_json(json)

