# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, BackboneElement, CodeableConcept, CodeableReference, Identifier, Quantity, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class DeviceDispensePerformer(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor: Reference = Field(alias="actor", serialization_alias="actor")
    function: CodeableConcept | None = Field(None, alias="function", serialization_alias="function")


class DeviceDispense(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='DeviceDispense',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='DeviceDispense'
    )
    
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    destination: Reference | None = Field(None, alias="destination", serialization_alias="destination")
    device: CodeableReference = Field(alias="device", serialization_alias="device")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    event_history: PyList[Reference] | None = Field(None, alias="eventHistory", serialization_alias="eventHistory")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    location: Reference | None = Field(None, alias="location", serialization_alias="location")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    part_of: PyList[Reference] | None = Field(None, alias="partOf", serialization_alias="partOf")
    performer: PyList[DeviceDispensePerformer] | None = Field(None, alias="performer", serialization_alias="performer")
    prepared_date: str | None = Field(None, alias="preparedDate", serialization_alias="preparedDate")
    quantity: Quantity | None = Field(None, alias="quantity", serialization_alias="quantity")
    receiver: Reference | None = Field(None, alias="receiver", serialization_alias="receiver")
    status: Literal["preparation", "in-progress", "cancelled", "on-hold", "completed", "entered-in-error", "stopped", "declined", "unknown"] = Field(alias="status", serialization_alias="status")
    status_reason: CodeableReference | None = Field(None, alias="statusReason", serialization_alias="statusReason")
    subject: Reference = Field(alias="subject", serialization_alias="subject")
    supporting_information: PyList[Reference] | None = Field(None, alias="supportingInformation", serialization_alias="supportingInformation")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    usage_instruction: str | None = Field(None, alias="usageInstruction", serialization_alias="usageInstruction")
    when_handed_over: str | None = Field(None, alias="whenHandedOver", serialization_alias="whenHandedOver")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> DeviceDispense:
        return cls.model_validate_json(json)

