# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, Attachment, BackboneElement, CodeableConcept, CodeableReference, Coding, ContactDetail, Identifier, \
    Period, ProductShelfLife, Quantity, Range, Reference, RelatedArtifact, UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class DeviceDefinitionChargeItem(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    charge_item_code: CodeableReference = Field(alias="chargeItemCode", serialization_alias="chargeItemCode")
    count: Quantity = Field(alias="count", serialization_alias="count")
    effective_period: Period | None = Field(None, alias="effectivePeriod", serialization_alias="effectivePeriod")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")

class DeviceDefinitionClassification(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    justification: PyList[RelatedArtifact] | None = Field(None, alias="justification", serialization_alias="justification")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class DeviceDefinitionConformsTo(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    category: CodeableConcept | None = Field(None, alias="category", serialization_alias="category")
    source: PyList[RelatedArtifact] | None = Field(None, alias="source", serialization_alias="source")
    specification: CodeableConcept = Field(alias="specification", serialization_alias="specification")
    version: PyList[str] | None = Field(None, alias="version", serialization_alias="version")

class DeviceDefinitionCorrectiveAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    period: Period = Field(alias="period", serialization_alias="period")
    recall: bool = Field(alias="recall", serialization_alias="recall")
    scope: Literal["model", "lot-numbers", "serial-numbers"] | None = Field(None, alias="scope", serialization_alias="scope")

class DeviceDefinitionDeviceName(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    name: str = Field(alias="name", serialization_alias="name")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class DeviceDefinitionDeviceVersion(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    component: Identifier | None = Field(None, alias="component", serialization_alias="component")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    value: str = Field(alias="value", serialization_alias="value")

class DeviceDefinitionGuideline(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    contraindication: PyList[CodeableConcept] | None = Field(None, alias="contraindication", serialization_alias="contraindication")
    indication: PyList[CodeableConcept] | None = Field(None, alias="indication", serialization_alias="indication")
    intended_use: str | None = Field(None, alias="intendedUse", serialization_alias="intendedUse")
    related_artifact: PyList[RelatedArtifact] | None = Field(None, alias="relatedArtifact", serialization_alias="relatedArtifact")
    usage_instruction: str | None = Field(None, alias="usageInstruction", serialization_alias="usageInstruction")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    warning: PyList[CodeableConcept] | None = Field(None, alias="warning", serialization_alias="warning")

class DeviceDefinitionHasPart(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    count: int | None = Field(None, alias="count", serialization_alias="count")
    reference: Reference = Field(alias="reference", serialization_alias="reference")

class DeviceDefinitionLink(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    related_device: CodeableReference = Field(alias="relatedDevice", serialization_alias="relatedDevice")
    relation: Coding = Field(alias="relation", serialization_alias="relation")

class DeviceDefinitionMaterial(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    allergenic_indicator: bool | None = Field(None, alias="allergenicIndicator", serialization_alias="allergenicIndicator")
    alternate: bool | None = Field(None, alias="alternate", serialization_alias="alternate")
    substance: CodeableConcept = Field(alias="substance", serialization_alias="substance")

class DeviceDefinitionPackaging(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    count: int | None = Field(None, alias="count", serialization_alias="count")
    distributor: PyList[DeviceDefinitionPackagingDistributor] | None = Field(None, alias="distributor", serialization_alias="distributor")
    identifier: Identifier | None = Field(None, alias="identifier", serialization_alias="identifier")
    packaging: PyList[DeviceDefinitionPackaging] | None = Field(None, alias="packaging", serialization_alias="packaging")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    udi_device_identifier: PyList[DeviceDefinitionUdiDeviceIdentifier] | None = Field(None, alias="udiDeviceIdentifier", serialization_alias="udiDeviceIdentifier")

class DeviceDefinitionPackagingDistributor(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    name: str | None = Field(None, alias="name", serialization_alias="name")
    organization_reference: PyList[Reference] | None = Field(None, alias="organizationReference", serialization_alias="organizationReference")

class DeviceDefinitionProperty(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    value_attachment: Attachment | None = Field(None, alias="valueAttachment", serialization_alias="valueAttachment")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_integer: int | None = Field(None, alias="valueInteger", serialization_alias="valueInteger")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_range: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")
    value_string: str | None = Field(None, alias="valueString", serialization_alias="valueString")

class DeviceDefinitionRegulatoryIdentifier(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    device_identifier: str = Field(alias="deviceIdentifier", serialization_alias="deviceIdentifier")
    issuer: str = Field(alias="issuer", serialization_alias="issuer")
    jurisdiction: str = Field(alias="jurisdiction", serialization_alias="jurisdiction")
    type: Literal["basic", "master", "license"] = Field(alias="type", serialization_alias="type")

class DeviceDefinitionUdiDeviceIdentifier(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    device_identifier: str = Field(alias="deviceIdentifier", serialization_alias="deviceIdentifier")
    issuer: str = Field(alias="issuer", serialization_alias="issuer")
    jurisdiction: str = Field(alias="jurisdiction", serialization_alias="jurisdiction")
    market_distribution: PyList[DeviceDefinitionUdiDeviceIdentifierMarketDistribution] | None = Field(None, alias="marketDistribution", serialization_alias="marketDistribution")

class DeviceDefinitionUdiDeviceIdentifierMarketDistribution(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    market_period: Period = Field(alias="marketPeriod", serialization_alias="marketPeriod")
    sub_jurisdiction: str = Field(alias="subJurisdiction", serialization_alias="subJurisdiction")


class DeviceDefinition(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='DeviceDefinition',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='DeviceDefinition'
    )
    
    charge_item: PyList[DeviceDefinitionChargeItem] | None = Field(None, alias="chargeItem", serialization_alias="chargeItem")
    classification: PyList[DeviceDefinitionClassification] | None = Field(None, alias="classification", serialization_alias="classification")
    conforms_to: PyList[DeviceDefinitionConformsTo] | None = Field(None, alias="conformsTo", serialization_alias="conformsTo")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    corrective_action: DeviceDefinitionCorrectiveAction | None = Field(None, alias="correctiveAction", serialization_alias="correctiveAction")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    device_name: PyList[DeviceDefinitionDeviceName] | None = Field(None, alias="deviceName", serialization_alias="deviceName")
    device_version: PyList[DeviceDefinitionDeviceVersion] | None = Field(None, alias="deviceVersion", serialization_alias="deviceVersion")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    guideline: DeviceDefinitionGuideline | None = Field(None, alias="guideline", serialization_alias="guideline")
    has_part: PyList[DeviceDefinitionHasPart] | None = Field(None, alias="hasPart", serialization_alias="hasPart")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    link: PyList[DeviceDefinitionLink] | None = Field(None, alias="link", serialization_alias="link")
    manufacturer: Reference | None = Field(None, alias="manufacturer", serialization_alias="manufacturer")
    material: PyList[DeviceDefinitionMaterial] | None = Field(None, alias="material", serialization_alias="material")
    model_number: str | None = Field(None, alias="modelNumber", serialization_alias="modelNumber")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    output_language: PyList[str] | None = Field(None, alias="outputLanguage", serialization_alias="outputLanguage")
    packaging: PyList[DeviceDefinitionPackaging] | None = Field(None, alias="packaging", serialization_alias="packaging")
    part_number: str | None = Field(None, alias="partNumber", serialization_alias="partNumber")
    production_identifier_in_udi: PyList[CodeableConcept] | None = Field(None, alias="productionIdentifierInUDI", serialization_alias="productionIdentifierInUDI")
    property: PyList[DeviceDefinitionProperty] | None = Field(None, alias="property", serialization_alias="property")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    regulatory_identifier: PyList[DeviceDefinitionRegulatoryIdentifier] | None = Field(None, alias="regulatoryIdentifier", serialization_alias="regulatoryIdentifier")
    safety: PyList[CodeableConcept] | None = Field(None, alias="safety", serialization_alias="safety")
    shelf_life_storage: PyList[ProductShelfLife] | None = Field(None, alias="shelfLifeStorage", serialization_alias="shelfLifeStorage")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    udi_device_identifier: PyList[DeviceDefinitionUdiDeviceIdentifier] | None = Field(None, alias="udiDeviceIdentifier", serialization_alias="udiDeviceIdentifier")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> DeviceDefinition:
        return cls.model_validate_json(json)

