# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, Attachment, BackboneElement, CodeableConcept, CodeableReference, ContactPoint, Identifier, \
    Quantity, Range, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class DeviceAdditive(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    performed: str | None = Field(None, alias="performed", serialization_alias="performed")
    performer: Reference | None = Field(None, alias="performer", serialization_alias="performer")
    quantity: Quantity | None = Field(None, alias="quantity", serialization_alias="quantity")
    type: CodeableReference = Field(alias="type", serialization_alias="type")

class DeviceConformsTo(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    category: CodeableConcept | None = Field(None, alias="category", serialization_alias="category")
    specification: CodeableConcept = Field(alias="specification", serialization_alias="specification")
    version: str | None = Field(None, alias="version", serialization_alias="version")

class DeviceDeviceVersion(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    component: Identifier | None = Field(None, alias="component", serialization_alias="component")
    install_date: str | None = Field(None, alias="installDate", serialization_alias="installDate")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    value: str = Field(alias="value", serialization_alias="value")

class DeviceName(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    display: bool | None = Field(None, alias="display", serialization_alias="display")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    value: str = Field(alias="value", serialization_alias="value")

class DeviceProperty(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    value_attachment: Attachment | None = Field(None, alias="valueAttachment", serialization_alias="valueAttachment")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_integer: int | None = Field(None, alias="valueInteger", serialization_alias="valueInteger")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_range: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")
    value_string: str | None = Field(None, alias="valueString", serialization_alias="valueString")

class DeviceUdiCarrier(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    carrier_aidc: str | None = Field(None, alias="carrierAIDC", serialization_alias="carrierAIDC")
    carrier_hrf: str | None = Field(None, alias="carrierHRF", serialization_alias="carrierHRF")
    device_identifier: str = Field(alias="deviceIdentifier", serialization_alias="deviceIdentifier")
    device_identifier_system: str | None = Field(None, alias="deviceIdentifierSystem", serialization_alias="deviceIdentifierSystem")
    entry_type: Literal["barcode", "rfid", "manual", "card", "self-reported", "electronic-transmission", "unknown"] | None = Field(None, alias="entryType", serialization_alias="entryType")
    issuer: str = Field(alias="issuer", serialization_alias="issuer")
    jurisdiction: str | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")


class Device(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Device',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Device'
    )
    
    additive: PyList[DeviceAdditive] | None = Field(None, alias="additive", serialization_alias="additive")
    availability_status: CodeableConcept | None = Field(None, alias="availabilityStatus", serialization_alias="availabilityStatus")
    biological_source_event: Identifier | None = Field(None, alias="biologicalSourceEvent", serialization_alias="biologicalSourceEvent")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    conforms_to: PyList[DeviceConformsTo] | None = Field(None, alias="conformsTo", serialization_alias="conformsTo")
    contact: PyList[ContactPoint] | None = Field(None, alias="contact", serialization_alias="contact")
    definition: Reference | None = Field(None, alias="definition", serialization_alias="definition")
    device_version: PyList[DeviceDeviceVersion] | None = Field(None, alias="deviceVersion", serialization_alias="deviceVersion")
    expiration_date: str | None = Field(None, alias="expirationDate", serialization_alias="expirationDate")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    location: Reference | None = Field(None, alias="location", serialization_alias="location")
    lot_number: str | None = Field(None, alias="lotNumber", serialization_alias="lotNumber")
    manufacture_date: str | None = Field(None, alias="manufactureDate", serialization_alias="manufactureDate")
    manufacturer: str | None = Field(None, alias="manufacturer", serialization_alias="manufacturer")
    model_number: str | None = Field(None, alias="modelNumber", serialization_alias="modelNumber")
    name: PyList[DeviceName] | None = Field(None, alias="name", serialization_alias="name")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    parent: Reference | None = Field(None, alias="parent", serialization_alias="parent")
    part_number: str | None = Field(None, alias="partNumber", serialization_alias="partNumber")
    property: PyList[DeviceProperty] | None = Field(None, alias="property", serialization_alias="property")
    safety: PyList[CodeableConcept] | None = Field(None, alias="safety", serialization_alias="safety")
    serial_number: str | None = Field(None, alias="serialNumber", serialization_alias="serialNumber")
    status: Literal["active", "inactive", "entered-in-error"] | None = Field(None, alias="status", serialization_alias="status")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")
    udi_carrier: PyList[DeviceUdiCarrier] | None = Field(None, alias="udiCarrier", serialization_alias="udiCarrier")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Device:
        return cls.model_validate_json(json)

