# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Attachment, BackboneElement, CodeableConcept, CodeableReference, Coding, Identifier, Period, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class DocumentReferenceAttester(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    mode: CodeableConcept = Field(alias="mode", serialization_alias="mode")
    party: Reference | None = Field(None, alias="party", serialization_alias="party")
    time: str | None = Field(None, alias="time", serialization_alias="time")

class DocumentReferenceContent(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    attachment: Attachment = Field(alias="attachment", serialization_alias="attachment")
    profile: PyList[DocumentReferenceContentProfile] | None = Field(None, alias="profile", serialization_alias="profile")

class DocumentReferenceContentProfile(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    value_canonical: str | None = Field(None, alias="valueCanonical", serialization_alias="valueCanonical")
    value_coding: Coding | None = Field(None, alias="valueCoding", serialization_alias="valueCoding")
    value_uri: str | None = Field(None, alias="valueUri", serialization_alias="valueUri")

class DocumentReferenceRelatesTo(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    target: Reference = Field(alias="target", serialization_alias="target")


class DocumentReference(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='DocumentReference',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='DocumentReference'
    )
    
    attester: PyList[DocumentReferenceAttester] | None = Field(None, alias="attester", serialization_alias="attester")
    author: PyList[Reference] | None = Field(None, alias="author", serialization_alias="author")
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    body_site: PyList[CodeableReference] | None = Field(None, alias="bodySite", serialization_alias="bodySite")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    content: PyList[DocumentReferenceContent] = Field(alias="content", serialization_alias="content")
    context: PyList[Reference] | None = Field(None, alias="context", serialization_alias="context")
    custodian: Reference | None = Field(None, alias="custodian", serialization_alias="custodian")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    doc_status: Literal["registered", "partial", "final", "amended", "cancelled", "entered-in-error", "deprecated", "unknown", "preliminary", "corrected", "appended"] | None = Field(None, alias="docStatus", serialization_alias="docStatus")
    event: PyList[CodeableReference] | None = Field(None, alias="event", serialization_alias="event")
    facility_type: CodeableConcept | None = Field(None, alias="facilityType", serialization_alias="facilityType")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    modality: PyList[CodeableConcept] | None = Field(None, alias="modality", serialization_alias="modality")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    practice_setting: CodeableConcept | None = Field(None, alias="practiceSetting", serialization_alias="practiceSetting")
    related: PyList[Reference] | None = Field(None, alias="related", serialization_alias="related")
    relates_to: PyList[DocumentReferenceRelatesTo] | None = Field(None, alias="relatesTo", serialization_alias="relatesTo")
    security_label: PyList[CodeableConcept] | None = Field(None, alias="securityLabel", serialization_alias="securityLabel")
    status: Literal["current", "superseded", "entered-in-error"] = Field(alias="status", serialization_alias="status")
    subject: Reference | None = Field(None, alias="subject", serialization_alias="subject")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> DocumentReference:
        return cls.model_validate_json(json)

