# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, CodeableReference, Duration, Identifier, Period, Reference, VirtualServiceDetail
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class EncounterAdmission(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    admit_source: CodeableConcept | None = Field(None, alias="admitSource", serialization_alias="admitSource")
    destination: Reference | None = Field(None, alias="destination", serialization_alias="destination")
    discharge_disposition: CodeableConcept | None = Field(None, alias="dischargeDisposition", serialization_alias="dischargeDisposition")
    origin: Reference | None = Field(None, alias="origin", serialization_alias="origin")
    pre_admission_identifier: Identifier | None = Field(None, alias="preAdmissionIdentifier", serialization_alias="preAdmissionIdentifier")
    re_admission: CodeableConcept | None = Field(None, alias="reAdmission", serialization_alias="reAdmission")

class EncounterDiagnosis(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    condition: PyList[CodeableReference] | None = Field(None, alias="condition", serialization_alias="condition")
    use: PyList[CodeableConcept] | None = Field(None, alias="use", serialization_alias="use")

class EncounterLocation(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    form: CodeableConcept | None = Field(None, alias="form", serialization_alias="form")
    location: Reference = Field(alias="location", serialization_alias="location")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    status: Literal["planned", "active", "reserved", "completed"] | None = Field(None, alias="status", serialization_alias="status")

class EncounterParticipant(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor: Reference | None = Field(None, alias="actor", serialization_alias="actor")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")

class EncounterReason(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    use: PyList[CodeableConcept] | None = Field(None, alias="use", serialization_alias="use")
    value: PyList[CodeableReference] | None = Field(None, alias="value", serialization_alias="value")


class Encounter(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Encounter',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Encounter'
    )
    
    account: PyList[Reference] | None = Field(None, alias="account", serialization_alias="account")
    actual_period: Period | None = Field(None, alias="actualPeriod", serialization_alias="actualPeriod")
    admission: EncounterAdmission | None = Field(None, alias="admission", serialization_alias="admission")
    appointment: PyList[Reference] | None = Field(None, alias="appointment", serialization_alias="appointment")
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    care_team: PyList[Reference] | None = Field(None, alias="careTeam", serialization_alias="careTeam")
    class_: PyList[CodeableConcept] | None = Field(None, alias="class", serialization_alias="class")
    diagnosis: PyList[EncounterDiagnosis] | None = Field(None, alias="diagnosis", serialization_alias="diagnosis")
    diet_preference: PyList[CodeableConcept] | None = Field(None, alias="dietPreference", serialization_alias="dietPreference")
    episode_of_care: PyList[Reference] | None = Field(None, alias="episodeOfCare", serialization_alias="episodeOfCare")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    length: Duration | None = Field(None, alias="length", serialization_alias="length")
    location: PyList[EncounterLocation] | None = Field(None, alias="location", serialization_alias="location")
    participant: PyList[EncounterParticipant] | None = Field(None, alias="participant", serialization_alias="participant")
    part_of: Reference | None = Field(None, alias="partOf", serialization_alias="partOf")
    planned_end_date: str | None = Field(None, alias="plannedEndDate", serialization_alias="plannedEndDate")
    planned_start_date: str | None = Field(None, alias="plannedStartDate", serialization_alias="plannedStartDate")
    priority: CodeableConcept | None = Field(None, alias="priority", serialization_alias="priority")
    reason: PyList[EncounterReason] | None = Field(None, alias="reason", serialization_alias="reason")
    service_provider: Reference | None = Field(None, alias="serviceProvider", serialization_alias="serviceProvider")
    service_type: PyList[CodeableReference] | None = Field(None, alias="serviceType", serialization_alias="serviceType")
    special_arrangement: PyList[CodeableConcept] | None = Field(None, alias="specialArrangement", serialization_alias="specialArrangement")
    special_courtesy: PyList[CodeableConcept] | None = Field(None, alias="specialCourtesy", serialization_alias="specialCourtesy")
    status: Literal["planned", "in-progress", "on-hold", "discharged", "completed", "cancelled", "discontinued", "entered-in-error", "unknown"] = Field(alias="status", serialization_alias="status")
    subject: Reference | None = Field(None, alias="subject", serialization_alias="subject")
    subject_status: CodeableConcept | None = Field(None, alias="subjectStatus", serialization_alias="subjectStatus")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")
    virtual_service: PyList[VirtualServiceDetail] | None = Field(None, alias="virtualService", serialization_alias="virtualService")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Encounter:
        return cls.model_validate_json(json)

