# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import CodeableConcept, Identifier
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class FormularyItem(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='FormularyItem',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='FormularyItem'
    )
    
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    status: Literal["active", "entered-in-error", "inactive"] | None = Field(None, alias="status", serialization_alias="status")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> FormularyItem:
        return cls.model_validate_json(json)

