# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, BackboneElement, CodeableConcept, CodeableReference, Identifier, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class GenomicStudyAnalysis(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    change_type: PyList[CodeableConcept] | None = Field(None, alias="changeType", serialization_alias="changeType")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    device: PyList[GenomicStudyAnalysisDevice] | None = Field(None, alias="device", serialization_alias="device")
    focus: PyList[Reference] | None = Field(None, alias="focus", serialization_alias="focus")
    genome_build: CodeableConcept | None = Field(None, alias="genomeBuild", serialization_alias="genomeBuild")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    input: PyList[GenomicStudyAnalysisInput] | None = Field(None, alias="input", serialization_alias="input")
    instantiates_canonical: str | None = Field(None, alias="instantiatesCanonical", serialization_alias="instantiatesCanonical")
    instantiates_uri: str | None = Field(None, alias="instantiatesUri", serialization_alias="instantiatesUri")
    method_type: PyList[CodeableConcept] | None = Field(None, alias="methodType", serialization_alias="methodType")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    output: PyList[GenomicStudyAnalysisOutput] | None = Field(None, alias="output", serialization_alias="output")
    performer: PyList[GenomicStudyAnalysisPerformer] | None = Field(None, alias="performer", serialization_alias="performer")
    protocol_performed: Reference | None = Field(None, alias="protocolPerformed", serialization_alias="protocolPerformed")
    regions_called: PyList[Reference] | None = Field(None, alias="regionsCalled", serialization_alias="regionsCalled")
    regions_studied: PyList[Reference] | None = Field(None, alias="regionsStudied", serialization_alias="regionsStudied")
    specimen: PyList[Reference] | None = Field(None, alias="specimen", serialization_alias="specimen")
    title: str | None = Field(None, alias="title", serialization_alias="title")

class GenomicStudyAnalysisDevice(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    device: Reference | None = Field(None, alias="device", serialization_alias="device")
    function: CodeableConcept | None = Field(None, alias="function", serialization_alias="function")

class GenomicStudyAnalysisInput(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    file: Reference | None = Field(None, alias="file", serialization_alias="file")
    generated_by_identifier: Identifier | None = Field(None, alias="generatedByIdentifier", serialization_alias="generatedByIdentifier")
    generated_by_reference: Reference | None = Field(None, alias="generatedByReference", serialization_alias="generatedByReference")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class GenomicStudyAnalysisOutput(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    file: Reference | None = Field(None, alias="file", serialization_alias="file")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class GenomicStudyAnalysisPerformer(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor: Reference | None = Field(None, alias="actor", serialization_alias="actor")
    role: CodeableConcept | None = Field(None, alias="role", serialization_alias="role")


class GenomicStudy(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='GenomicStudy',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='GenomicStudy'
    )
    
    analysis: PyList[GenomicStudyAnalysis] | None = Field(None, alias="analysis", serialization_alias="analysis")
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    instantiates_canonical: str | None = Field(None, alias="instantiatesCanonical", serialization_alias="instantiatesCanonical")
    instantiates_uri: str | None = Field(None, alias="instantiatesUri", serialization_alias="instantiatesUri")
    interpreter: PyList[Reference] | None = Field(None, alias="interpreter", serialization_alias="interpreter")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    reason: PyList[CodeableReference] | None = Field(None, alias="reason", serialization_alias="reason")
    referrer: Reference | None = Field(None, alias="referrer", serialization_alias="referrer")
    start_date: str | None = Field(None, alias="startDate", serialization_alias="startDate")
    status: Literal["registered", "available", "cancelled", "entered-in-error", "unknown"] = Field(alias="status", serialization_alias="status")
    subject: Reference = Field(alias="subject", serialization_alias="subject")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> GenomicStudy:
        return cls.model_validate_json(json)

