# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Coding, ContactDetail, Duration, Expression, Identifier, Period, Quantity, \
    Range, Reference, RelativeTime, UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class GroupCharacteristic(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    determined_by_expression: Expression | None = Field(None, alias="determinedByExpression", serialization_alias="determinedByExpression")
    determined_by_reference: Reference | None = Field(None, alias="determinedByReference", serialization_alias="determinedByReference")
    duration_duration: Duration | None = Field(None, alias="durationDuration", serialization_alias="durationDuration")
    duration_range: Range | None = Field(None, alias="durationRange", serialization_alias="durationRange")
    exclude: bool = Field(alias="exclude", serialization_alias="exclude")
    instances_range: Range | None = Field(None, alias="instancesRange", serialization_alias="instancesRange")
    instances_unsigned_int: int | None = Field(None, alias="instancesUnsignedInt", serialization_alias="instancesUnsignedInt")
    method: PyList[CodeableConcept] | None = Field(None, alias="method", serialization_alias="method")
    offset: CodeableConcept | None = Field(None, alias="offset", serialization_alias="offset")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    timing: PyList[RelativeTime] | None = Field(None, alias="timing", serialization_alias="timing")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_expression: Expression | None = Field(None, alias="valueExpression", serialization_alias="valueExpression")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_range: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")
    value_reference: Reference | None = Field(None, alias="valueReference", serialization_alias="valueReference")
    value_uri: str | None = Field(None, alias="valueUri", serialization_alias="valueUri")

class GroupMember(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    entity: Reference = Field(alias="entity", serialization_alias="entity")
    inactive: bool | None = Field(None, alias="inactive", serialization_alias="inactive")
    involvement: PyList[CodeableConcept] | None = Field(None, alias="involvement", serialization_alias="involvement")
    period: Period | None = Field(None, alias="period", serialization_alias="period")


class Group(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Group',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Group'
    )
    
    characteristic: PyList[GroupCharacteristic] | None = Field(None, alias="characteristic", serialization_alias="characteristic")
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    combination_method: Literal["all-of", "any-of", "at-least", "at-most", "except-subset"] | None = Field(None, alias="combinationMethod", serialization_alias="combinationMethod")
    combination_threshold: PositiveInt | None = Field(None, alias="combinationThreshold", serialization_alias="combinationThreshold")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    managing_entity: Reference | None = Field(None, alias="managingEntity", serialization_alias="managingEntity")
    member: PyList[GroupMember] | None = Field(None, alias="member", serialization_alias="member")
    membership: Literal["definitional", "conceptual", "enumerated"] = Field(alias="membership", serialization_alias="membership")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    quantity: int | None = Field(None, alias="quantity", serialization_alias="quantity")
    status: Literal["draft", "active", "retired", "unknown"] | None = Field(None, alias="status", serialization_alias="status")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    type: Literal["person", "animal", "practitioner", "device", "careteam", "healthcareservice", "location", "organization", "relatedperson", "specimen", "medication", "substance", "biologicallyDerivedProduct", "nutritionProduct"] | None = Field(None, alias="type", serialization_alias="type")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Group:
        return cls.model_validate_json(json)

