# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, CodeableReference, Identifier, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ImagingSelectionImageRegion3D(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    coordinate: PyList[float] = Field(alias="coordinate", serialization_alias="coordinate")
    region_type: Literal["point", "multipoint", "polyline", "polygon", "ellipse", "ellipsoid"] = Field(alias="regionType", serialization_alias="regionType")

class ImagingSelectionInstance(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    image_region2d: PyList[ImagingSelectionInstanceImageRegion2D] | None = Field(None, alias="imageRegion2D", serialization_alias="imageRegion2D")
    number: int | None = Field(None, alias="number", serialization_alias="number")
    sop_class: str | None = Field(None, alias="sopClass", serialization_alias="sopClass")
    subset: PyList[str] | None = Field(None, alias="subset", serialization_alias="subset")
    uid: str = Field(alias="uid", serialization_alias="uid")

class ImagingSelectionInstanceImageRegion2D(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    coordinate: PyList[float] = Field(alias="coordinate", serialization_alias="coordinate")
    region_type: Literal["point", "polyline", "multipoint", "circle", "ellipse"] = Field(alias="regionType", serialization_alias="regionType")

class ImagingSelectionPerformer(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor: Reference | None = Field(None, alias="actor", serialization_alias="actor")
    function: CodeableConcept | None = Field(None, alias="function", serialization_alias="function")


class ImagingSelection(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ImagingSelection',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ImagingSelection'
    )
    
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    body_site: PyList[CodeableReference] | None = Field(None, alias="bodySite", serialization_alias="bodySite")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    derived_from: Reference | None = Field(None, alias="derivedFrom", serialization_alias="derivedFrom")
    endpoint: PyList[Reference] | None = Field(None, alias="endpoint", serialization_alias="endpoint")
    focus: PyList[Reference] | None = Field(None, alias="focus", serialization_alias="focus")
    frame_of_reference_uid: str | None = Field(None, alias="frameOfReferenceUid", serialization_alias="frameOfReferenceUid")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    image_region3d: PyList[ImagingSelectionImageRegion3D] | None = Field(None, alias="imageRegion3D", serialization_alias="imageRegion3D")
    instance: PyList[ImagingSelectionInstance] | None = Field(None, alias="instance", serialization_alias="instance")
    issued: str | None = Field(None, alias="issued", serialization_alias="issued")
    performer: PyList[ImagingSelectionPerformer] | None = Field(None, alias="performer", serialization_alias="performer")
    series_number: int | None = Field(None, alias="seriesNumber", serialization_alias="seriesNumber")
    series_uid: str | None = Field(None, alias="seriesUid", serialization_alias="seriesUid")
    status: Literal["available", "entered-in-error", "inactive", "unknown"] = Field(alias="status", serialization_alias="status")
    study_uid: str | None = Field(None, alias="studyUid", serialization_alias="studyUid")
    subject: Reference | None = Field(None, alias="subject", serialization_alias="subject")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ImagingSelection:
        return cls.model_validate_json(json)

