# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, BackboneElement, CodeableConcept, CodeableReference, Identifier, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ImagingStudySeries(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    body_site: CodeableReference | None = Field(None, alias="bodySite", serialization_alias="bodySite")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    endpoint: PyList[Reference] | None = Field(None, alias="endpoint", serialization_alias="endpoint")
    instance: PyList[ImagingStudySeriesInstance] | None = Field(None, alias="instance", serialization_alias="instance")
    laterality: CodeableConcept | None = Field(None, alias="laterality", serialization_alias="laterality")
    modality: CodeableConcept = Field(alias="modality", serialization_alias="modality")
    number: int | None = Field(None, alias="number", serialization_alias="number")
    number_of_instances: int | None = Field(None, alias="numberOfInstances", serialization_alias="numberOfInstances")
    performer: PyList[ImagingStudySeriesPerformer] | None = Field(None, alias="performer", serialization_alias="performer")
    specimen: PyList[Reference] | None = Field(None, alias="specimen", serialization_alias="specimen")
    started: str | None = Field(None, alias="started", serialization_alias="started")
    uid: str = Field(alias="uid", serialization_alias="uid")

class ImagingStudySeriesInstance(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    number: int | None = Field(None, alias="number", serialization_alias="number")
    sop_class: str = Field(alias="sopClass", serialization_alias="sopClass")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    uid: str = Field(alias="uid", serialization_alias="uid")

class ImagingStudySeriesPerformer(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor: Reference = Field(alias="actor", serialization_alias="actor")
    function: CodeableConcept | None = Field(None, alias="function", serialization_alias="function")


class ImagingStudy(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ImagingStudy',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ImagingStudy'
    )
    
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    endpoint: PyList[Reference] | None = Field(None, alias="endpoint", serialization_alias="endpoint")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    location: Reference | None = Field(None, alias="location", serialization_alias="location")
    modality: PyList[CodeableConcept] | None = Field(None, alias="modality", serialization_alias="modality")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    number_of_instances: int | None = Field(None, alias="numberOfInstances", serialization_alias="numberOfInstances")
    number_of_series: int | None = Field(None, alias="numberOfSeries", serialization_alias="numberOfSeries")
    part_of: PyList[Reference] | None = Field(None, alias="partOf", serialization_alias="partOf")
    procedure: PyList[CodeableReference] | None = Field(None, alias="procedure", serialization_alias="procedure")
    reason: PyList[CodeableReference] | None = Field(None, alias="reason", serialization_alias="reason")
    referrer: Reference | None = Field(None, alias="referrer", serialization_alias="referrer")
    series: PyList[ImagingStudySeries] | None = Field(None, alias="series", serialization_alias="series")
    started: str | None = Field(None, alias="started", serialization_alias="started")
    status: Literal["registered", "available", "cancelled", "entered-in-error", "unknown", "inactive"] = Field(alias="status", serialization_alias="status")
    subject: Reference = Field(alias="subject", serialization_alias="subject")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ImagingStudy:
        return cls.model_validate_json(json)

