# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, BackboneElement, CodeableConcept, CodeableReference, Identifier, Period, Quantity, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class InventoryReportInventoryListing(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    counting_date_time: str | None = Field(None, alias="countingDateTime", serialization_alias="countingDateTime")
    item: PyList[InventoryReportInventoryListingItem] | None = Field(None, alias="item", serialization_alias="item")
    item_status: CodeableConcept | None = Field(None, alias="itemStatus", serialization_alias="itemStatus")
    location: Reference | None = Field(None, alias="location", serialization_alias="location")

class InventoryReportInventoryListingItem(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    category: CodeableConcept | None = Field(None, alias="category", serialization_alias="category")
    item: CodeableReference = Field(alias="item", serialization_alias="item")
    quantity: Quantity = Field(alias="quantity", serialization_alias="quantity")


class InventoryReport(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='InventoryReport',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='InventoryReport'
    )
    
    count_type: Literal["snapshot", "difference"] = Field(alias="countType", serialization_alias="countType")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    inventory_listing: PyList[InventoryReportInventoryListing] | None = Field(None, alias="inventoryListing", serialization_alias="inventoryListing")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    operation_type: CodeableConcept | None = Field(None, alias="operationType", serialization_alias="operationType")
    operation_type_reason: CodeableConcept | None = Field(None, alias="operationTypeReason", serialization_alias="operationTypeReason")
    reported_date_time: str = Field(alias="reportedDateTime", serialization_alias="reportedDateTime")
    reporter: Reference | None = Field(None, alias="reporter", serialization_alias="reporter")
    reporting_period: Period | None = Field(None, alias="reportingPeriod", serialization_alias="reportingPeriod")
    status: Literal["draft", "requested", "active", "entered-in-error"] = Field(alias="status", serialization_alias="status")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> InventoryReport:
        return cls.model_validate_json(json)

