# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Address, Availability, BackboneElement, CodeableConcept, Coding, ExtendedContactDetail, Identifier, Reference, \
    VirtualServiceDetail
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class LocationPosition(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    altitude: float | None = Field(None, alias="altitude", serialization_alias="altitude")
    latitude: float = Field(alias="latitude", serialization_alias="latitude")
    longitude: float = Field(alias="longitude", serialization_alias="longitude")


class Location(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Location',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Location'
    )
    
    address: Address | None = Field(None, alias="address", serialization_alias="address")
    alias: PyList[str] | None = Field(None, alias="alias", serialization_alias="alias")
    characteristic: PyList[CodeableConcept] | None = Field(None, alias="characteristic", serialization_alias="characteristic")
    contact: PyList[ExtendedContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    endpoint: PyList[Reference] | None = Field(None, alias="endpoint", serialization_alias="endpoint")
    form: CodeableConcept | None = Field(None, alias="form", serialization_alias="form")
    hours_of_operation: Availability | None = Field(None, alias="hoursOfOperation", serialization_alias="hoursOfOperation")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    managing_organization: Reference | None = Field(None, alias="managingOrganization", serialization_alias="managingOrganization")
    mode: Literal["instance", "kind"] | None = Field(None, alias="mode", serialization_alias="mode")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    operational_status: Coding | None = Field(None, alias="operationalStatus", serialization_alias="operationalStatus")
    part_of: Reference | None = Field(None, alias="partOf", serialization_alias="partOf")
    position: LocationPosition | None = Field(None, alias="position", serialization_alias="position")
    status: Literal["active", "suspended", "inactive"] | None = Field(None, alias="status", serialization_alias="status")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")
    virtual_service: PyList[VirtualServiceDetail] | None = Field(None, alias="virtualService", serialization_alias="virtualService")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Location:
        return cls.model_validate_json(json)

