# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Attachment, BackboneElement, CodeableConcept, CodeableReference, Identifier, MarketingStatus, Quantity, \
    Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ManufacturedItemDefinitionComponent(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    amount: PyList[Quantity] | None = Field(None, alias="amount", serialization_alias="amount")
    component: PyList[ManufacturedItemDefinitionComponent] | None = Field(None, alias="component", serialization_alias="component")
    constituent: PyList[ManufacturedItemDefinitionComponentConstituent] | None = Field(None, alias="constituent", serialization_alias="constituent")
    function: PyList[CodeableConcept] | None = Field(None, alias="function", serialization_alias="function")
    property: PyList[ManufacturedItemDefinitionProperty] | None = Field(None, alias="property", serialization_alias="property")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class ManufacturedItemDefinitionComponentConstituent(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    amount: PyList[Quantity] | None = Field(None, alias="amount", serialization_alias="amount")
    function: PyList[CodeableConcept] | None = Field(None, alias="function", serialization_alias="function")
    has_ingredient: PyList[CodeableReference] | None = Field(None, alias="hasIngredient", serialization_alias="hasIngredient")
    location: PyList[CodeableConcept] | None = Field(None, alias="location", serialization_alias="location")

class ManufacturedItemDefinitionProperty(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    value_attachment: Attachment | None = Field(None, alias="valueAttachment", serialization_alias="valueAttachment")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_date: str | None = Field(None, alias="valueDate", serialization_alias="valueDate")
    value_markdown: str | None = Field(None, alias="valueMarkdown", serialization_alias="valueMarkdown")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_reference: Reference | None = Field(None, alias="valueReference", serialization_alias="valueReference")


class ManufacturedItemDefinition(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ManufacturedItemDefinition',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ManufacturedItemDefinition'
    )
    
    component: PyList[ManufacturedItemDefinitionComponent] | None = Field(None, alias="component", serialization_alias="component")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    ingredient: PyList[CodeableConcept] | None = Field(None, alias="ingredient", serialization_alias="ingredient")
    manufactured_dose_form: CodeableConcept = Field(alias="manufacturedDoseForm", serialization_alias="manufacturedDoseForm")
    manufacturer: PyList[Reference] | None = Field(None, alias="manufacturer", serialization_alias="manufacturer")
    marketing_status: PyList[MarketingStatus] | None = Field(None, alias="marketingStatus", serialization_alias="marketingStatus")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    property: PyList[ManufacturedItemDefinitionProperty] | None = Field(None, alias="property", serialization_alias="property")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    unit_of_presentation: CodeableConcept | None = Field(None, alias="unitOfPresentation", serialization_alias="unitOfPresentation")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ManufacturedItemDefinition:
        return cls.model_validate_json(json)

