# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, Attachment, BackboneElement, CodeableConcept, CodeableReference, ContactDetail, Dosage, Duration, \
    Identifier, Money, Period, Quantity, Range, Ratio, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class MedicationKnowledgeCost(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    cost_codeable_concept: CodeableConcept | None = Field(None, alias="costCodeableConcept", serialization_alias="costCodeableConcept")
    cost_money: Money | None = Field(None, alias="costMoney", serialization_alias="costMoney")
    effective_date: PyList[Period] | None = Field(None, alias="effectiveDate", serialization_alias="effectiveDate")
    source: str | None = Field(None, alias="source", serialization_alias="source")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class MedicationKnowledgeDefinitional(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    definition: PyList[Reference] | None = Field(None, alias="definition", serialization_alias="definition")
    dose_form: CodeableConcept | None = Field(None, alias="doseForm", serialization_alias="doseForm")
    drug_characteristic: PyList[MedicationKnowledgeDefinitionalDrugCharacteristic] | None = Field(None, alias="drugCharacteristic", serialization_alias="drugCharacteristic")
    ingredient: PyList[MedicationKnowledgeDefinitionalIngredient] | None = Field(None, alias="ingredient", serialization_alias="ingredient")
    intended_route: PyList[CodeableConcept] | None = Field(None, alias="intendedRoute", serialization_alias="intendedRoute")

class MedicationKnowledgeDefinitionalDrugCharacteristic(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    value_attachment: Attachment | None = Field(None, alias="valueAttachment", serialization_alias="valueAttachment")
    value_base64binary: str | None = Field(None, alias="valueBase64Binary", serialization_alias="valueBase64Binary")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_string: str | None = Field(None, alias="valueString", serialization_alias="valueString")

class MedicationKnowledgeDefinitionalIngredient(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    item: CodeableReference = Field(alias="item", serialization_alias="item")
    strength_codeable_concept: CodeableConcept | None = Field(None, alias="strengthCodeableConcept", serialization_alias="strengthCodeableConcept")
    strength_quantity: Quantity | None = Field(None, alias="strengthQuantity", serialization_alias="strengthQuantity")
    strength_ratio: Ratio | None = Field(None, alias="strengthRatio", serialization_alias="strengthRatio")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class MedicationKnowledgeIndicationGuideline(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    dosing_guideline: PyList[MedicationKnowledgeIndicationGuidelineDosingGuideline] | None = Field(None, alias="dosingGuideline", serialization_alias="dosingGuideline")
    indication: PyList[CodeableReference] | None = Field(None, alias="indication", serialization_alias="indication")

class MedicationKnowledgeIndicationGuidelineDosingGuideline(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    administration_treatment: CodeableConcept | None = Field(None, alias="administrationTreatment", serialization_alias="administrationTreatment")
    dosage: PyList[MedicationKnowledgeIndicationGuidelineDosingGuidelineDosage] | None = Field(None, alias="dosage", serialization_alias="dosage")
    patient_characteristic: PyList[MedicationKnowledgeIndicationGuidelineDosingGuidelinePatientCharacteristic] | None = Field(None, alias="patientCharacteristic", serialization_alias="patientCharacteristic")
    treatment_intent: CodeableConcept | None = Field(None, alias="treatmentIntent", serialization_alias="treatmentIntent")

class MedicationKnowledgeIndicationGuidelineDosingGuidelineDosage(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    dosage: PyList[Dosage] = Field(alias="dosage", serialization_alias="dosage")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class MedicationKnowledgeIndicationGuidelineDosingGuidelinePatientCharacteristic(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_range: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")

class MedicationKnowledgeMedicineClassification(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    classification: PyList[CodeableConcept] | None = Field(None, alias="classification", serialization_alias="classification")
    source_string: str | None = Field(None, alias="sourceString", serialization_alias="sourceString")
    source_uri: str | None = Field(None, alias="sourceUri", serialization_alias="sourceUri")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class MedicationKnowledgeMonitoringProgram(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    name: str | None = Field(None, alias="name", serialization_alias="name")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class MedicationKnowledgeMonograph(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    source: Reference | None = Field(None, alias="source", serialization_alias="source")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class MedicationKnowledgePackaging(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    cost: PyList[MedicationKnowledgeCost] | None = Field(None, alias="cost", serialization_alias="cost")
    packaged_product: Reference | None = Field(None, alias="packagedProduct", serialization_alias="packagedProduct")

class MedicationKnowledgeRegulatory(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    max_dispense: MedicationKnowledgeRegulatoryMaxDispense | None = Field(None, alias="maxDispense", serialization_alias="maxDispense")
    regulatory_authority: Reference = Field(alias="regulatoryAuthority", serialization_alias="regulatoryAuthority")
    schedule: PyList[CodeableConcept] | None = Field(None, alias="schedule", serialization_alias="schedule")
    substitution: PyList[MedicationKnowledgeRegulatorySubstitution] | None = Field(None, alias="substitution", serialization_alias="substitution")

class MedicationKnowledgeRegulatoryMaxDispense(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    period: Duration | None = Field(None, alias="period", serialization_alias="period")
    quantity: Quantity = Field(alias="quantity", serialization_alias="quantity")

class MedicationKnowledgeRegulatorySubstitution(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    allowed: bool = Field(alias="allowed", serialization_alias="allowed")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class MedicationKnowledgeRelatedMedicationKnowledge(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    reference: PyList[Reference] = Field(alias="reference", serialization_alias="reference")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class MedicationKnowledgeStorageGuideline(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    environmental_setting: PyList[MedicationKnowledgeStorageGuidelineEnvironmentalSetting] | None = Field(None, alias="environmentalSetting", serialization_alias="environmentalSetting")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    reference: str | None = Field(None, alias="reference", serialization_alias="reference")
    stability_duration: Duration | None = Field(None, alias="stabilityDuration", serialization_alias="stabilityDuration")

class MedicationKnowledgeStorageGuidelineEnvironmentalSetting(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")
    value_range: Range | None = Field(None, alias="valueRange", serialization_alias="valueRange")


class MedicationKnowledge(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='MedicationKnowledge',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='MedicationKnowledge'
    )
    
    associated_medication: PyList[Reference] | None = Field(None, alias="associatedMedication", serialization_alias="associatedMedication")
    author: ContactDetail | None = Field(None, alias="author", serialization_alias="author")
    clinical_use_issue: PyList[Reference] | None = Field(None, alias="clinicalUseIssue", serialization_alias="clinicalUseIssue")
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    cost: PyList[MedicationKnowledgeCost] | None = Field(None, alias="cost", serialization_alias="cost")
    definitional: MedicationKnowledgeDefinitional | None = Field(None, alias="definitional", serialization_alias="definitional")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    indication_guideline: PyList[MedicationKnowledgeIndicationGuideline] | None = Field(None, alias="indicationGuideline", serialization_alias="indicationGuideline")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    medicine_classification: PyList[MedicationKnowledgeMedicineClassification] | None = Field(None, alias="medicineClassification", serialization_alias="medicineClassification")
    monitoring_program: PyList[MedicationKnowledgeMonitoringProgram] | None = Field(None, alias="monitoringProgram", serialization_alias="monitoringProgram")
    monograph: PyList[MedicationKnowledgeMonograph] | None = Field(None, alias="monograph", serialization_alias="monograph")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    packaging: PyList[MedicationKnowledgePackaging] | None = Field(None, alias="packaging", serialization_alias="packaging")
    preparation_instruction: str | None = Field(None, alias="preparationInstruction", serialization_alias="preparationInstruction")
    product_type: PyList[CodeableConcept] | None = Field(None, alias="productType", serialization_alias="productType")
    regulatory: PyList[MedicationKnowledgeRegulatory] | None = Field(None, alias="regulatory", serialization_alias="regulatory")
    related_medication_knowledge: PyList[MedicationKnowledgeRelatedMedicationKnowledge] | None = Field(None, alias="relatedMedicationKnowledge", serialization_alias="relatedMedicationKnowledge")
    status: Literal["draft", "active", "retired", "unknown"] | None = Field(None, alias="status", serialization_alias="status")
    storage_guideline: PyList[MedicationKnowledgeStorageGuideline] | None = Field(None, alias="storageGuideline", serialization_alias="storageGuideline")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> MedicationKnowledge:
        return cls.model_validate_json(json)

