# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, BackboneElement, CodeableConcept, CodeableReference, Dosage, Identifier, Period, Reference, \
    Timing
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class MedicationStatementAdherence(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    reason: CodeableConcept | None = Field(None, alias="reason", serialization_alias="reason")


class MedicationStatement(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='MedicationStatement',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='MedicationStatement'
    )
    
    adherence: MedicationStatementAdherence | None = Field(None, alias="adherence", serialization_alias="adherence")
    author: Reference | None = Field(None, alias="author", serialization_alias="author")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    date_asserted: str | None = Field(None, alias="dateAsserted", serialization_alias="dateAsserted")
    derived_from: PyList[Reference] | None = Field(None, alias="derivedFrom", serialization_alias="derivedFrom")
    dosage: PyList[Dosage] | None = Field(None, alias="dosage", serialization_alias="dosage")
    effective_date_time: str | None = Field(None, alias="effectiveDateTime", serialization_alias="effectiveDateTime")
    effective_period: Period | None = Field(None, alias="effectivePeriod", serialization_alias="effectivePeriod")
    effective_timing: Timing | None = Field(None, alias="effectiveTiming", serialization_alias="effectiveTiming")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    information_source: PyList[Reference] | None = Field(None, alias="informationSource", serialization_alias="informationSource")
    medication: CodeableReference = Field(alias="medication", serialization_alias="medication")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    part_of: PyList[Reference] | None = Field(None, alias="partOf", serialization_alias="partOf")
    reason: PyList[CodeableReference] | None = Field(None, alias="reason", serialization_alias="reason")
    related_clinical_information: PyList[Reference] | None = Field(None, alias="relatedClinicalInformation", serialization_alias="relatedClinicalInformation")
    rendered_dosage_instruction: str | None = Field(None, alias="renderedDosageInstruction", serialization_alias="renderedDosageInstruction")
    status: Literal["recorded", "entered-in-error", "draft"] = Field(alias="status", serialization_alias="status")
    subject: Reference = Field(alias="subject", serialization_alias="subject")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> MedicationStatement:
        return cls.model_validate_json(json)

