# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, BackboneElement, CodeableConcept, CodeableReference, Identifier, Period, Quantity, Ratio, \
    Reference, Timing
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class MedicationAdministrationDosage(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    dose: Quantity | None = Field(None, alias="dose", serialization_alias="dose")
    method: CodeableConcept | None = Field(None, alias="method", serialization_alias="method")
    rate_quantity: Quantity | None = Field(None, alias="rateQuantity", serialization_alias="rateQuantity")
    rate_ratio: Ratio | None = Field(None, alias="rateRatio", serialization_alias="rateRatio")
    route: CodeableConcept | None = Field(None, alias="route", serialization_alias="route")
    site: CodeableConcept | None = Field(None, alias="site", serialization_alias="site")
    text: str | None = Field(None, alias="text", serialization_alias="text")

class MedicationAdministrationPerformer(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor: CodeableReference = Field(alias="actor", serialization_alias="actor")
    function: CodeableConcept | None = Field(None, alias="function", serialization_alias="function")


class MedicationAdministration(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='MedicationAdministration',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='MedicationAdministration'
    )
    
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    device: PyList[CodeableReference] | None = Field(None, alias="device", serialization_alias="device")
    dosage: MedicationAdministrationDosage | None = Field(None, alias="dosage", serialization_alias="dosage")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    event_history: PyList[Reference] | None = Field(None, alias="eventHistory", serialization_alias="eventHistory")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    is_sub_potent: bool | None = Field(None, alias="isSubPotent", serialization_alias="isSubPotent")
    medication: CodeableReference = Field(alias="medication", serialization_alias="medication")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    occurrence_date_time: str | None = Field(None, alias="occurrenceDateTime", serialization_alias="occurrenceDateTime")
    occurrence_period: Period | None = Field(None, alias="occurrencePeriod", serialization_alias="occurrencePeriod")
    occurrence_timing: Timing | None = Field(None, alias="occurrenceTiming", serialization_alias="occurrenceTiming")
    part_of: PyList[Reference] | None = Field(None, alias="partOf", serialization_alias="partOf")
    performer: PyList[MedicationAdministrationPerformer] | None = Field(None, alias="performer", serialization_alias="performer")
    reason: PyList[CodeableReference] | None = Field(None, alias="reason", serialization_alias="reason")
    recorded: str | None = Field(None, alias="recorded", serialization_alias="recorded")
    request: Reference | None = Field(None, alias="request", serialization_alias="request")
    status: Literal["in-progress", "not-done", "on-hold", "completed", "entered-in-error", "stopped", "unknown"] = Field(alias="status", serialization_alias="status")
    status_reason: PyList[CodeableConcept] | None = Field(None, alias="statusReason", serialization_alias="statusReason")
    subject: Reference = Field(alias="subject", serialization_alias="subject")
    sub_potent_reason: PyList[CodeableConcept] | None = Field(None, alias="subPotentReason", serialization_alias="subPotentReason")
    supporting_information: PyList[Reference] | None = Field(None, alias="supportingInformation", serialization_alias="supportingInformation")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> MedicationAdministration:
        return cls.model_validate_json(json)

