# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Attachment, BackboneElement, CodeableConcept, CodeableReference, Coding, Identifier, MarketingStatus, \
    Period, Quantity, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class MedicinalProductDefinitionCharacteristic(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    value_attachment: Attachment | None = Field(None, alias="valueAttachment", serialization_alias="valueAttachment")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_date: str | None = Field(None, alias="valueDate", serialization_alias="valueDate")
    value_integer: int | None = Field(None, alias="valueInteger", serialization_alias="valueInteger")
    value_markdown: str | None = Field(None, alias="valueMarkdown", serialization_alias="valueMarkdown")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")

class MedicinalProductDefinitionContact(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    contact: Reference = Field(alias="contact", serialization_alias="contact")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class MedicinalProductDefinitionCrossReference(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    product: CodeableReference = Field(alias="product", serialization_alias="product")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class MedicinalProductDefinitionName(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    part: PyList[MedicinalProductDefinitionNamePart] | None = Field(None, alias="part", serialization_alias="part")
    product_name: str = Field(alias="productName", serialization_alias="productName")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    usage: PyList[MedicinalProductDefinitionNameUsage] | None = Field(None, alias="usage", serialization_alias="usage")

class MedicinalProductDefinitionNamePart(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    part: str = Field(alias="part", serialization_alias="part")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class MedicinalProductDefinitionNameUsage(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    country: CodeableConcept = Field(alias="country", serialization_alias="country")
    jurisdiction: CodeableConcept | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    language: CodeableConcept = Field(alias="language", serialization_alias="language")

class MedicinalProductDefinitionOperation(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    confidentiality_indicator: CodeableConcept | None = Field(None, alias="confidentialityIndicator", serialization_alias="confidentialityIndicator")
    effective_date: Period | None = Field(None, alias="effectiveDate", serialization_alias="effectiveDate")
    organization: PyList[Reference] | None = Field(None, alias="organization", serialization_alias="organization")
    type: CodeableReference | None = Field(None, alias="type", serialization_alias="type")


class MedicinalProductDefinition(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='MedicinalProductDefinition',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='MedicinalProductDefinition'
    )
    
    additional_monitoring_indicator: CodeableConcept | None = Field(None, alias="additionalMonitoringIndicator", serialization_alias="additionalMonitoringIndicator")
    attached_document: PyList[Reference] | None = Field(None, alias="attachedDocument", serialization_alias="attachedDocument")
    characteristic: PyList[MedicinalProductDefinitionCharacteristic] | None = Field(None, alias="characteristic", serialization_alias="characteristic")
    classification: PyList[CodeableConcept] | None = Field(None, alias="classification", serialization_alias="classification")
    clinical_trial: PyList[Reference] | None = Field(None, alias="clinicalTrial", serialization_alias="clinicalTrial")
    code: PyList[Coding] | None = Field(None, alias="code", serialization_alias="code")
    combined_pharmaceutical_dose_form: CodeableConcept | None = Field(None, alias="combinedPharmaceuticalDoseForm", serialization_alias="combinedPharmaceuticalDoseForm")
    comprised_of: PyList[Reference] | None = Field(None, alias="comprisedOf", serialization_alias="comprisedOf")
    contact: PyList[MedicinalProductDefinitionContact] | None = Field(None, alias="contact", serialization_alias="contact")
    cross_reference: PyList[MedicinalProductDefinitionCrossReference] | None = Field(None, alias="crossReference", serialization_alias="crossReference")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    domain: CodeableConcept | None = Field(None, alias="domain", serialization_alias="domain")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    impurity: PyList[CodeableReference] | None = Field(None, alias="impurity", serialization_alias="impurity")
    indication: str | None = Field(None, alias="indication", serialization_alias="indication")
    ingredient: PyList[CodeableConcept] | None = Field(None, alias="ingredient", serialization_alias="ingredient")
    legal_status_of_supply: CodeableConcept | None = Field(None, alias="legalStatusOfSupply", serialization_alias="legalStatusOfSupply")
    marketing_status: PyList[MarketingStatus] | None = Field(None, alias="marketingStatus", serialization_alias="marketingStatus")
    master_file: PyList[Reference] | None = Field(None, alias="masterFile", serialization_alias="masterFile")
    name: PyList[MedicinalProductDefinitionName] = Field(alias="name", serialization_alias="name")
    operation: PyList[MedicinalProductDefinitionOperation] | None = Field(None, alias="operation", serialization_alias="operation")
    packaged_medicinal_product: PyList[CodeableConcept] | None = Field(None, alias="packagedMedicinalProduct", serialization_alias="packagedMedicinalProduct")
    pediatric_use_indicator: CodeableConcept | None = Field(None, alias="pediatricUseIndicator", serialization_alias="pediatricUseIndicator")
    route: PyList[CodeableConcept] | None = Field(None, alias="route", serialization_alias="route")
    special_measures: PyList[CodeableConcept] | None = Field(None, alias="specialMeasures", serialization_alias="specialMeasures")
    status: CodeableConcept | None = Field(None, alias="status", serialization_alias="status")
    status_date: str | None = Field(None, alias="statusDate", serialization_alias="statusDate")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> MedicinalProductDefinition:
        return cls.model_validate_json(json)

