# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Attachment, BackboneElement, CodeableConcept, Identifier, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class MolecularSequenceConcatenated(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    sequence_element: PyList[MolecularSequenceConcatenatedSequenceElement] = Field(alias="sequenceElement", serialization_alias="sequenceElement")

class MolecularSequenceConcatenatedSequenceElement(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    ordinal_index: int = Field(alias="ordinalIndex", serialization_alias="ordinalIndex")
    sequence: Reference = Field(alias="sequence", serialization_alias="sequence")

class MolecularSequenceExtracted(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    coordinate_system: CodeableConcept = Field(alias="coordinateSystem", serialization_alias="coordinateSystem")
    end: int = Field(alias="end", serialization_alias="end")
    reverse_complement: bool | None = Field(None, alias="reverseComplement", serialization_alias="reverseComplement")
    start: int = Field(alias="start", serialization_alias="start")
    starting_sequence: Reference = Field(alias="startingSequence", serialization_alias="startingSequence")

class MolecularSequenceLiteral(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    sequence_value: str = Field(alias="sequenceValue", serialization_alias="sequenceValue")

class MolecularSequenceRelative(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    edit: PyList[MolecularSequenceRelativeEdit] | None = Field(None, alias="edit", serialization_alias="edit")
    starting_sequence: Reference = Field(alias="startingSequence", serialization_alias="startingSequence")

class MolecularSequenceRelativeEdit(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    coordinate_system: CodeableConcept = Field(alias="coordinateSystem", serialization_alias="coordinateSystem")
    edit_order: int | None = Field(None, alias="editOrder", serialization_alias="editOrder")
    end: int = Field(alias="end", serialization_alias="end")
    replaced_sequence: Reference | None = Field(None, alias="replacedSequence", serialization_alias="replacedSequence")
    replacement_sequence: Reference = Field(alias="replacementSequence", serialization_alias="replacementSequence")
    start: int = Field(alias="start", serialization_alias="start")

class MolecularSequenceRepeated(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    copy_count: int = Field(alias="copyCount", serialization_alias="copyCount")
    sequence_motif: Reference = Field(alias="sequenceMotif", serialization_alias="sequenceMotif")


class MolecularSequence(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='MolecularSequence',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='MolecularSequence'
    )
    
    concatenated: MolecularSequenceConcatenated | None = Field(None, alias="concatenated", serialization_alias="concatenated")
    extracted: PyList[MolecularSequenceExtracted] | None = Field(None, alias="extracted", serialization_alias="extracted")
    file: PyList[Attachment] | None = Field(None, alias="file", serialization_alias="file")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    literal: PyList[MolecularSequenceLiteral] | None = Field(None, alias="literal", serialization_alias="literal")
    relative: PyList[MolecularSequenceRelative] | None = Field(None, alias="relative", serialization_alias="relative")
    repeated: PyList[MolecularSequenceRepeated] | None = Field(None, alias="repeated", serialization_alias="repeated")
    type: Literal["aa", "dna", "rna"] | None = Field(None, alias="type", serialization_alias="type")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> MolecularSequence:
        return cls.model_validate_json(json)

