# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Coding, ContactDetail, Identifier, Period, Range, Reference, UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ObservationDefinitionComponent(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    permitted_data_type: PyList[Literal["Quantity", "CodeableConcept", "string", "boolean", "integer", "Range", "Ratio", "SampledData", "time", "dateTime", "Period"]] | None = Field(None, alias="permittedDataType", serialization_alias="permittedDataType")
    permitted_unit: PyList[Coding] | None = Field(None, alias="permittedUnit", serialization_alias="permittedUnit")
    qualified_value: PyList[ObservationDefinitionQualifiedValue] | None = Field(None, alias="qualifiedValue", serialization_alias="qualifiedValue")

class ObservationDefinitionQualifiedValue(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    abnormal_coded_value_set: str | None = Field(None, alias="abnormalCodedValueSet", serialization_alias="abnormalCodedValueSet")
    age: Range | None = Field(None, alias="age", serialization_alias="age")
    applies_to: PyList[CodeableConcept] | None = Field(None, alias="appliesTo", serialization_alias="appliesTo")
    condition: str | None = Field(None, alias="condition", serialization_alias="condition")
    context: CodeableConcept | None = Field(None, alias="context", serialization_alias="context")
    critical_coded_value_set: str | None = Field(None, alias="criticalCodedValueSet", serialization_alias="criticalCodedValueSet")
    gender: Literal["male", "female", "other", "unknown"] | None = Field(None, alias="gender", serialization_alias="gender")
    gestational_age: Range | None = Field(None, alias="gestationalAge", serialization_alias="gestationalAge")
    interpretation: PyList[CodeableConcept] | None = Field(None, alias="interpretation", serialization_alias="interpretation")
    normal_coded_value_set: str | None = Field(None, alias="normalCodedValueSet", serialization_alias="normalCodedValueSet")
    range: Range | None = Field(None, alias="range", serialization_alias="range")
    range_category: Literal["reference", "critical", "absolute"] | None = Field(None, alias="rangeCategory", serialization_alias="rangeCategory")
    valid_coded_value_set: str | None = Field(None, alias="validCodedValueSet", serialization_alias="validCodedValueSet")


class ObservationDefinition(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ObservationDefinition',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ObservationDefinition'
    )
    
    approval_date: str | None = Field(None, alias="approvalDate", serialization_alias="approvalDate")
    body_site: CodeableConcept | None = Field(None, alias="bodySite", serialization_alias="bodySite")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    component: PyList[ObservationDefinitionComponent] | None = Field(None, alias="component", serialization_alias="component")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    derived_from_canonical: PyList[str] | None = Field(None, alias="derivedFromCanonical", serialization_alias="derivedFromCanonical")
    derived_from_uri: PyList[str] | None = Field(None, alias="derivedFromUri", serialization_alias="derivedFromUri")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    device: PyList[Reference] | None = Field(None, alias="device", serialization_alias="device")
    effective_period: Period | None = Field(None, alias="effectivePeriod", serialization_alias="effectivePeriod")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    has_member: PyList[Reference] | None = Field(None, alias="hasMember", serialization_alias="hasMember")
    identifier: Identifier | None = Field(None, alias="identifier", serialization_alias="identifier")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    last_review_date: str | None = Field(None, alias="lastReviewDate", serialization_alias="lastReviewDate")
    method: CodeableConcept | None = Field(None, alias="method", serialization_alias="method")
    multiple_results_allowed: bool | None = Field(None, alias="multipleResultsAllowed", serialization_alias="multipleResultsAllowed")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    performer_type: CodeableConcept | None = Field(None, alias="performerType", serialization_alias="performerType")
    permitted_data_type: PyList[Literal["Quantity", "CodeableConcept", "string", "boolean", "integer", "Range", "Ratio", "SampledData", "time", "dateTime", "Period"]] | None = Field(None, alias="permittedDataType", serialization_alias="permittedDataType")
    permitted_unit: PyList[Coding] | None = Field(None, alias="permittedUnit", serialization_alias="permittedUnit")
    preferred_report_name: str | None = Field(None, alias="preferredReportName", serialization_alias="preferredReportName")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    qualified_value: PyList[ObservationDefinitionQualifiedValue] | None = Field(None, alias="qualifiedValue", serialization_alias="qualifiedValue")
    specimen: PyList[Reference] | None = Field(None, alias="specimen", serialization_alias="specimen")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    subject: PyList[CodeableConcept] | None = Field(None, alias="subject", serialization_alias="subject")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ObservationDefinition:
        return cls.model_validate_json(json)

