# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, ExtendedContactDetail, Identifier, Period, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class OrganizationQualification(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    issuer: Reference | None = Field(None, alias="issuer", serialization_alias="issuer")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    status: CodeableConcept | None = Field(None, alias="status", serialization_alias="status")


class Organization(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Organization',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Organization'
    )
    
    active: bool | None = Field(None, alias="active", serialization_alias="active")
    alias: PyList[str] | None = Field(None, alias="alias", serialization_alias="alias")
    contact: PyList[ExtendedContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    endpoint: PyList[Reference] | None = Field(None, alias="endpoint", serialization_alias="endpoint")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    part_of: Reference | None = Field(None, alias="partOf", serialization_alias="partOf")
    qualification: PyList[OrganizationQualification] | None = Field(None, alias="qualification", serialization_alias="qualification")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Organization:
        return cls.model_validate_json(json)

