# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    CodeableConcept, ExtendedContactDetail, Identifier, Period, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class OrganizationAffiliation(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='OrganizationAffiliation',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='OrganizationAffiliation'
    )
    
    active: bool | None = Field(None, alias="active", serialization_alias="active")
    code: PyList[CodeableConcept] | None = Field(None, alias="code", serialization_alias="code")
    contact: PyList[ExtendedContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    endpoint: PyList[Reference] | None = Field(None, alias="endpoint", serialization_alias="endpoint")
    healthcare_service: PyList[Reference] | None = Field(None, alias="healthcareService", serialization_alias="healthcareService")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    location: PyList[Reference] | None = Field(None, alias="location", serialization_alias="location")
    network: PyList[Reference] | None = Field(None, alias="network", serialization_alias="network")
    organization: Reference | None = Field(None, alias="organization", serialization_alias="organization")
    participating_organization: Reference | None = Field(None, alias="participatingOrganization", serialization_alias="participatingOrganization")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    specialty: PyList[CodeableConcept] | None = Field(None, alias="specialty", serialization_alias="specialty")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> OrganizationAffiliation:
        return cls.model_validate_json(json)

