# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import CodeableConcept, Period, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class PersonalRelationship(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='PersonalRelationship',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='PersonalRelationship'
    )
    
    asserter: Reference | None = Field(None, alias="asserter", serialization_alias="asserter")
    confidence: CodeableConcept | None = Field(None, alias="confidence", serialization_alias="confidence")
    group: PyList[Reference] | None = Field(None, alias="group", serialization_alias="group")
    period: PyList[Period] | None = Field(None, alias="period", serialization_alias="period")
    relationship_type: CodeableConcept = Field(alias="relationshipType", serialization_alias="relationshipType")
    source: Reference = Field(alias="source", serialization_alias="source")
    target: Reference = Field(alias="target", serialization_alias="target")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> PersonalRelationship:
        return cls.model_validate_json(json)

