# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Age, Annotation, BackboneElement, CodeableConcept, CodeableReference, Identifier, Period, Range, Reference, \
    Timing
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ProcedureFocalDevice(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: CodeableConcept | None = Field(None, alias="action", serialization_alias="action")
    manipulated: Reference = Field(alias="manipulated", serialization_alias="manipulated")

class ProcedurePerformer(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor: Reference = Field(alias="actor", serialization_alias="actor")
    function: CodeableConcept | None = Field(None, alias="function", serialization_alias="function")
    on_behalf_of: Reference | None = Field(None, alias="onBehalfOf", serialization_alias="onBehalfOf")
    period: Period | None = Field(None, alias="period", serialization_alias="period")


class Procedure(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='Procedure',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='Procedure'
    )
    
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    body_site: PyList[CodeableConcept] | None = Field(None, alias="bodySite", serialization_alias="bodySite")
    body_structure: PyList[Reference] | None = Field(None, alias="bodyStructure", serialization_alias="bodyStructure")
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    complication: PyList[CodeableReference] | None = Field(None, alias="complication", serialization_alias="complication")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    focal_device: PyList[ProcedureFocalDevice] | None = Field(None, alias="focalDevice", serialization_alias="focalDevice")
    focus: Reference | None = Field(None, alias="focus", serialization_alias="focus")
    follow_up: PyList[CodeableReference] | None = Field(None, alias="followUp", serialization_alias="followUp")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    location: Reference | None = Field(None, alias="location", serialization_alias="location")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    occurrence_age: Age | None = Field(None, alias="occurrenceAge", serialization_alias="occurrenceAge")
    occurrence_date_time: str | None = Field(None, alias="occurrenceDateTime", serialization_alias="occurrenceDateTime")
    occurrence_period: Period | None = Field(None, alias="occurrencePeriod", serialization_alias="occurrencePeriod")
    occurrence_range: Range | None = Field(None, alias="occurrenceRange", serialization_alias="occurrenceRange")
    occurrence_string: str | None = Field(None, alias="occurrenceString", serialization_alias="occurrenceString")
    occurrence_timing: Timing | None = Field(None, alias="occurrenceTiming", serialization_alias="occurrenceTiming")
    outcome: PyList[CodeableReference] | None = Field(None, alias="outcome", serialization_alias="outcome")
    part_of: PyList[Reference] | None = Field(None, alias="partOf", serialization_alias="partOf")
    performer: PyList[ProcedurePerformer] | None = Field(None, alias="performer", serialization_alias="performer")
    reason: PyList[CodeableReference] | None = Field(None, alias="reason", serialization_alias="reason")
    recorded: str | None = Field(None, alias="recorded", serialization_alias="recorded")
    recorder: Reference | None = Field(None, alias="recorder", serialization_alias="recorder")
    report: PyList[Reference] | None = Field(None, alias="report", serialization_alias="report")
    reported_boolean: bool | None = Field(None, alias="reportedBoolean", serialization_alias="reportedBoolean")
    reported_reference: Reference | None = Field(None, alias="reportedReference", serialization_alias="reportedReference")
    status: Literal["preparation", "in-progress", "not-done", "on-hold", "stopped", "completed", "entered-in-error", "unknown"] = Field(alias="status", serialization_alias="status")
    status_reason: CodeableConcept | None = Field(None, alias="statusReason", serialization_alias="statusReason")
    subject: Reference = Field(alias="subject", serialization_alias="subject")
    supporting_info: PyList[Reference] | None = Field(None, alias="supportingInfo", serialization_alias="supportingInfo")
    used: PyList[CodeableReference] | None = Field(None, alias="used", serialization_alias="used")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> Procedure:
        return cls.model_validate_json(json)

