# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Age, Annotation, BackboneElement, CodeableConcept, CodeableReference, DataRequirement, Duration, Expression, \
    Identifier, Period, Range, Reference, RelatedArtifact, Timing
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class RequestOrchestrationAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: PyList[RequestOrchestrationAction] | None = Field(None, alias="action", serialization_alias="action")
    cardinality_behavior: Literal["single", "multiple"] | None = Field(None, alias="cardinalityBehavior", serialization_alias="cardinalityBehavior")
    code: PyList[CodeableConcept] | None = Field(None, alias="code", serialization_alias="code")
    condition: PyList[RequestOrchestrationActionCondition] | None = Field(None, alias="condition", serialization_alias="condition")
    definition_canonical: str | None = Field(None, alias="definitionCanonical", serialization_alias="definitionCanonical")
    definition_uri: str | None = Field(None, alias="definitionUri", serialization_alias="definitionUri")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    documentation: PyList[RelatedArtifact] | None = Field(None, alias="documentation", serialization_alias="documentation")
    dynamic_value: PyList[RequestOrchestrationActionDynamicValue] | None = Field(None, alias="dynamicValue", serialization_alias="dynamicValue")
    goal: PyList[Reference] | None = Field(None, alias="goal", serialization_alias="goal")
    grouping_behavior: Literal["visual-group", "logical-group", "sentence-group"] | None = Field(None, alias="groupingBehavior", serialization_alias="groupingBehavior")
    input: PyList[RequestOrchestrationActionInput] | None = Field(None, alias="input", serialization_alias="input")
    link_id: str | None = Field(None, alias="linkId", serialization_alias="linkId")
    location: CodeableReference | None = Field(None, alias="location", serialization_alias="location")
    output: PyList[RequestOrchestrationActionOutput] | None = Field(None, alias="output", serialization_alias="output")
    participant: PyList[RequestOrchestrationActionParticipant] | None = Field(None, alias="participant", serialization_alias="participant")
    precheck_behavior: Literal["yes", "no"] | None = Field(None, alias="precheckBehavior", serialization_alias="precheckBehavior")
    prefix: str | None = Field(None, alias="prefix", serialization_alias="prefix")
    priority: Literal["routine", "urgent", "asap", "stat"] | None = Field(None, alias="priority", serialization_alias="priority")
    related_action: PyList[RequestOrchestrationActionRelatedAction] | None = Field(None, alias="relatedAction", serialization_alias="relatedAction")
    required_behavior: Literal["must", "could", "must-unless-documented"] | None = Field(None, alias="requiredBehavior", serialization_alias="requiredBehavior")
    resource: Reference | None = Field(None, alias="resource", serialization_alias="resource")
    selection_behavior: Literal["any", "all", "all-or-none", "exactly-one", "at-most-one", "one-or-more"] | None = Field(None, alias="selectionBehavior", serialization_alias="selectionBehavior")
    text_equivalent: str | None = Field(None, alias="textEquivalent", serialization_alias="textEquivalent")
    timing_age: Age | None = Field(None, alias="timingAge", serialization_alias="timingAge")
    timing_date_time: str | None = Field(None, alias="timingDateTime", serialization_alias="timingDateTime")
    timing_duration: Duration | None = Field(None, alias="timingDuration", serialization_alias="timingDuration")
    timing_period: Period | None = Field(None, alias="timingPeriod", serialization_alias="timingPeriod")
    timing_range: Range | None = Field(None, alias="timingRange", serialization_alias="timingRange")
    timing_timing: Timing | None = Field(None, alias="timingTiming", serialization_alias="timingTiming")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    transform: str | None = Field(None, alias="transform", serialization_alias="transform")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class RequestOrchestrationActionCondition(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    expression: Expression | None = Field(None, alias="expression", serialization_alias="expression")
    kind: Literal["applicability", "start", "stop"] = Field(alias="kind", serialization_alias="kind")

class RequestOrchestrationActionDynamicValue(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    expression: Expression | None = Field(None, alias="expression", serialization_alias="expression")
    path: str | None = Field(None, alias="path", serialization_alias="path")

class RequestOrchestrationActionInput(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    related_data: str | None = Field(None, alias="relatedData", serialization_alias="relatedData")
    requirement: DataRequirement | None = Field(None, alias="requirement", serialization_alias="requirement")
    title: str | None = Field(None, alias="title", serialization_alias="title")

class RequestOrchestrationActionOutput(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    related_data: str | None = Field(None, alias="relatedData", serialization_alias="relatedData")
    requirement: DataRequirement | None = Field(None, alias="requirement", serialization_alias="requirement")
    title: str | None = Field(None, alias="title", serialization_alias="title")

class RequestOrchestrationActionParticipant(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor_canonical: str | None = Field(None, alias="actorCanonical", serialization_alias="actorCanonical")
    actor_reference: Reference | None = Field(None, alias="actorReference", serialization_alias="actorReference")
    function: CodeableConcept | None = Field(None, alias="function", serialization_alias="function")
    role: CodeableConcept | None = Field(None, alias="role", serialization_alias="role")
    type: Literal["careteam", "device", "group", "healthcareservice", "location", "organization", "patient", "practitioner", "practitionerrole", "relatedperson"] | None = Field(None, alias="type", serialization_alias="type")
    type_canonical: str | None = Field(None, alias="typeCanonical", serialization_alias="typeCanonical")
    type_reference: Reference | None = Field(None, alias="typeReference", serialization_alias="typeReference")

class RequestOrchestrationActionRelatedAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    end_relationship: Literal["before", "concurrent", "after", "before-start", "before-end", "concurrent-with-start", "concurrent-with-end", "after-start", "after-end"] | None = Field(None, alias="endRelationship", serialization_alias="endRelationship")
    offset_duration: Duration | None = Field(None, alias="offsetDuration", serialization_alias="offsetDuration")
    offset_range: Range | None = Field(None, alias="offsetRange", serialization_alias="offsetRange")
    relationship: Literal["before", "concurrent", "after", "before-start", "before-end", "concurrent-with-start", "concurrent-with-end", "after-start", "after-end"] = Field(alias="relationship", serialization_alias="relationship")
    target_id: str = Field(alias="targetId", serialization_alias="targetId")


class RequestOrchestration(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='RequestOrchestration',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='RequestOrchestration'
    )
    
    action: PyList[RequestOrchestrationAction] | None = Field(None, alias="action", serialization_alias="action")
    author: Reference | None = Field(None, alias="author", serialization_alias="author")
    authored_on: str | None = Field(None, alias="authoredOn", serialization_alias="authoredOn")
    based_on: PyList[Reference] | None = Field(None, alias="basedOn", serialization_alias="basedOn")
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    encounter: Reference | None = Field(None, alias="encounter", serialization_alias="encounter")
    goal: PyList[Reference] | None = Field(None, alias="goal", serialization_alias="goal")
    group_identifier: Identifier | None = Field(None, alias="groupIdentifier", serialization_alias="groupIdentifier")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    instantiates_canonical: PyList[str] | None = Field(None, alias="instantiatesCanonical", serialization_alias="instantiatesCanonical")
    instantiates_uri: PyList[str] | None = Field(None, alias="instantiatesUri", serialization_alias="instantiatesUri")
    intent: Literal["proposal", "plan", "directive", "order", "option", "original-order", "reflex-order", "filler-order", "instance-order"] = Field(alias="intent", serialization_alias="intent")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    priority: Literal["routine", "urgent", "asap", "stat"] | None = Field(None, alias="priority", serialization_alias="priority")
    reason: PyList[CodeableReference] | None = Field(None, alias="reason", serialization_alias="reason")
    replaces: PyList[Reference] | None = Field(None, alias="replaces", serialization_alias="replaces")
    status: Literal["draft", "active", "on-hold", "entered-in-error", "ended", "unknown", "completed", "revoked"] = Field(alias="status", serialization_alias="status")
    subject: Reference | None = Field(None, alias="subject", serialization_alias="subject")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> RequestOrchestration:
        return cls.model_validate_json(json)

