# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Identifier, Period, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ResearchSubjectSubjectMilestone(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    date: str | None = Field(None, alias="date", serialization_alias="date")
    milestone: PyList[CodeableConcept] = Field(alias="milestone", serialization_alias="milestone")
    reason: CodeableConcept | None = Field(None, alias="reason", serialization_alias="reason")

class ResearchSubjectSubjectState(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableConcept = Field(alias="code", serialization_alias="code")
    end_date: str | None = Field(None, alias="endDate", serialization_alias="endDate")
    reason: CodeableConcept | None = Field(None, alias="reason", serialization_alias="reason")
    start_date: str = Field(alias="startDate", serialization_alias="startDate")


class ResearchSubject(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ResearchSubject',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ResearchSubject'
    )
    
    actual_comparison_group: str | None = Field(None, alias="actualComparisonGroup", serialization_alias="actualComparisonGroup")
    assigned_comparison_group: str | None = Field(None, alias="assignedComparisonGroup", serialization_alias="assignedComparisonGroup")
    consent: PyList[Reference] | None = Field(None, alias="consent", serialization_alias="consent")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    study: Reference = Field(alias="study", serialization_alias="study")
    subject: Reference = Field(alias="subject", serialization_alias="subject")
    subject_milestone: PyList[ResearchSubjectSubjectMilestone] | None = Field(None, alias="subjectMilestone", serialization_alias="subjectMilestone")
    subject_state: PyList[ResearchSubjectSubjectState] | None = Field(None, alias="subjectState", serialization_alias="subjectState")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ResearchSubject:
        return cls.model_validate_json(json)

