# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, Attachment, BackboneElement, CodeableConcept, CodeableReference, Identifier, Period, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class ResearchStudyAssociatedParty(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    classifier: PyList[CodeableConcept] | None = Field(None, alias="classifier", serialization_alias="classifier")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    party: Reference | None = Field(None, alias="party", serialization_alias="party")
    period: PyList[Period] | None = Field(None, alias="period", serialization_alias="period")
    role: CodeableConcept = Field(alias="role", serialization_alias="role")

class ResearchStudyComparisonGroup(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actual_number: int | None = Field(None, alias="actualNumber", serialization_alias="actualNumber")
    eligibility: Reference | None = Field(None, alias="eligibility", serialization_alias="eligibility")
    observed_group: Reference | None = Field(None, alias="observedGroup", serialization_alias="observedGroup")
    target_number: int | None = Field(None, alias="targetNumber", serialization_alias="targetNumber")

class ResearchStudyLabel(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")
    value: str | None = Field(None, alias="value", serialization_alias="value")

class ResearchStudyObjective(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    description: str | None = Field(None, alias="description", serialization_alias="description")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    outcome_measure: PyList[ResearchStudyObjectiveOutcomeMeasure] | None = Field(None, alias="outcomeMeasure", serialization_alias="outcomeMeasure")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class ResearchStudyObjectiveOutcomeMeasure(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    comparator: Reference | None = Field(None, alias="comparator", serialization_alias="comparator")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    endpoint: Reference = Field(alias="endpoint", serialization_alias="endpoint")
    event_handling: PyList[ResearchStudyObjectiveOutcomeMeasureEventHandling] | None = Field(None, alias="eventHandling", serialization_alias="eventHandling")
    intervention: Reference | None = Field(None, alias="intervention", serialization_alias="intervention")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    population: Reference | None = Field(None, alias="population", serialization_alias="population")
    summary_measure: CodeableConcept | None = Field(None, alias="summaryMeasure", serialization_alias="summaryMeasure")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class ResearchStudyObjectiveOutcomeMeasureEventHandling(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    description: str | None = Field(None, alias="description", serialization_alias="description")
    event: CodeableConcept | None = Field(None, alias="event", serialization_alias="event")
    group: CodeableConcept | None = Field(None, alias="group", serialization_alias="group")
    handling: CodeableConcept | None = Field(None, alias="handling", serialization_alias="handling")

class ResearchStudyProgressStatus(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actual: bool | None = Field(None, alias="actual", serialization_alias="actual")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    state: CodeableConcept = Field(alias="state", serialization_alias="state")

class ResearchStudyRecruitment(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actual_group: Reference | None = Field(None, alias="actualGroup", serialization_alias="actualGroup")
    actual_number: int | None = Field(None, alias="actualNumber", serialization_alias="actualNumber")
    eligibility: Reference | None = Field(None, alias="eligibility", serialization_alias="eligibility")
    target_number: int | None = Field(None, alias="targetNumber", serialization_alias="targetNumber")

class ResearchStudyRelatesTo(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    target_attachment: Attachment | None = Field(None, alias="targetAttachment", serialization_alias="targetAttachment")
    target_canonical: str | None = Field(None, alias="targetCanonical", serialization_alias="targetCanonical")
    target_markdown: str | None = Field(None, alias="targetMarkdown", serialization_alias="targetMarkdown")
    target_reference: Reference | None = Field(None, alias="targetReference", serialization_alias="targetReference")
    target_uri: str | None = Field(None, alias="targetUri", serialization_alias="targetUri")
    type: Literal["documentation", "justification", "predecessor", "successor", "derived-from", "depends-on", "composed-of", "part-of", "amends", "amended-with", "appends", "appended-with", "cites", "cited-by", "comments-on", "comment-in", "contains", "contained-in", "corrects", "correction-in", "replaces", "replaced-with", "retracts", "retracted-by", "signs", "similar-to", "supports", "supported-with", "transforms", "transformed-into", "transformed-with", "specification-of", "created-with", "cite-as", "summarizes"] = Field(alias="type", serialization_alias="type")


class ResearchStudy(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='ResearchStudy',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='ResearchStudy'
    )
    
    associated_party: PyList[ResearchStudyAssociatedParty] | None = Field(None, alias="associatedParty", serialization_alias="associatedParty")
    cite_as: str | None = Field(None, alias="citeAs", serialization_alias="citeAs")
    classifier: PyList[CodeableConcept] | None = Field(None, alias="classifier", serialization_alias="classifier")
    comparison_group: PyList[ResearchStudyComparisonGroup] | None = Field(None, alias="comparisonGroup", serialization_alias="comparisonGroup")
    condition: PyList[CodeableConcept] | None = Field(None, alias="condition", serialization_alias="condition")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    description_summary: str | None = Field(None, alias="descriptionSummary", serialization_alias="descriptionSummary")
    focus: PyList[CodeableReference] | None = Field(None, alias="focus", serialization_alias="focus")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    keyword: PyList[CodeableConcept] | None = Field(None, alias="keyword", serialization_alias="keyword")
    label: PyList[ResearchStudyLabel] | None = Field(None, alias="label", serialization_alias="label")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    objective: PyList[ResearchStudyObjective] | None = Field(None, alias="objective", serialization_alias="objective")
    part_of: PyList[Reference] | None = Field(None, alias="partOf", serialization_alias="partOf")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    phase: CodeableConcept | None = Field(None, alias="phase", serialization_alias="phase")
    primary_purpose_type: CodeableConcept | None = Field(None, alias="primaryPurposeType", serialization_alias="primaryPurposeType")
    progress_status: PyList[ResearchStudyProgressStatus] | None = Field(None, alias="progressStatus", serialization_alias="progressStatus")
    protocol: PyList[Reference] | None = Field(None, alias="protocol", serialization_alias="protocol")
    recruitment: ResearchStudyRecruitment | None = Field(None, alias="recruitment", serialization_alias="recruitment")
    region: PyList[CodeableConcept] | None = Field(None, alias="region", serialization_alias="region")
    relates_to: PyList[ResearchStudyRelatesTo] | None = Field(None, alias="relatesTo", serialization_alias="relatesTo")
    result: PyList[Reference] | None = Field(None, alias="result", serialization_alias="result")
    site: PyList[Reference] | None = Field(None, alias="site", serialization_alias="site")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    study_design: PyList[CodeableConcept] | None = Field(None, alias="studyDesign", serialization_alias="studyDesign")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    why_stopped: CodeableConcept | None = Field(None, alias="whyStopped", serialization_alias="whyStopped")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> ResearchStudy:
        return cls.model_validate_json(json)

