# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Coding, ContactDetail, Identifier, UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class StructureMapConst(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    name: str | None = Field(None, alias="name", serialization_alias="name")
    value: str | None = Field(None, alias="value", serialization_alias="value")

class StructureMapGroup(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    documentation: str | None = Field(None, alias="documentation", serialization_alias="documentation")
    extends: str | None = Field(None, alias="extends", serialization_alias="extends")
    input: PyList[StructureMapGroupInput] = Field(alias="input", serialization_alias="input")
    name: str = Field(alias="name", serialization_alias="name")
    rule: PyList[StructureMapGroupRule] | None = Field(None, alias="rule", serialization_alias="rule")
    type_mode: Literal["types", "type-and-types"] | None = Field(None, alias="typeMode", serialization_alias="typeMode")

class StructureMapGroupInput(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    documentation: str | None = Field(None, alias="documentation", serialization_alias="documentation")
    mode: Literal["source", "target"] = Field(alias="mode", serialization_alias="mode")
    name: str = Field(alias="name", serialization_alias="name")
    type: str | None = Field(None, alias="type", serialization_alias="type")

class StructureMapGroupRule(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    dependent: PyList[StructureMapGroupRuleDependent] | None = Field(None, alias="dependent", serialization_alias="dependent")
    documentation: str | None = Field(None, alias="documentation", serialization_alias="documentation")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    rule: PyList[StructureMapGroupRule] | None = Field(None, alias="rule", serialization_alias="rule")
    source: PyList[StructureMapGroupRuleSource] = Field(alias="source", serialization_alias="source")
    target: PyList[StructureMapGroupRuleTarget] | None = Field(None, alias="target", serialization_alias="target")

class StructureMapGroupRuleDependent(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    name: str = Field(alias="name", serialization_alias="name")
    parameter: PyList[StructureMapGroupRuleTargetParameter] = Field(alias="parameter", serialization_alias="parameter")

class StructureMapGroupRuleSource(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    check: str | None = Field(None, alias="check", serialization_alias="check")
    condition: str | None = Field(None, alias="condition", serialization_alias="condition")
    context: str = Field(alias="context", serialization_alias="context")
    default_value: str | None = Field(None, alias="defaultValue", serialization_alias="defaultValue")
    element: str | None = Field(None, alias="element", serialization_alias="element")
    list_mode: Literal["first", "not_first", "last", "not_last", "only_one"] | None = Field(None, alias="listMode", serialization_alias="listMode")
    log_message: str | None = Field(None, alias="logMessage", serialization_alias="logMessage")
    max: str | None = Field(None, alias="max", serialization_alias="max")
    min: int | None = Field(None, alias="min", serialization_alias="min")
    type: str | None = Field(None, alias="type", serialization_alias="type")
    variable: str | None = Field(None, alias="variable", serialization_alias="variable")

class StructureMapGroupRuleTarget(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    context: str | None = Field(None, alias="context", serialization_alias="context")
    element: str | None = Field(None, alias="element", serialization_alias="element")
    list_mode: PyList[Literal["first", "share", "last", "single"]] | None = Field(None, alias="listMode", serialization_alias="listMode")
    list_rule_id: str | None = Field(None, alias="listRuleId", serialization_alias="listRuleId")
    parameter: PyList[StructureMapGroupRuleTargetParameter] | None = Field(None, alias="parameter", serialization_alias="parameter")
    transform: Literal["create", "copy", "truncate", "escape", "cast", "append", "translate", "reference", "dateOp", "uuid", "pointer", "evaluate", "cc", "c", "qty", "id", "cp"] | None = Field(None, alias="transform", serialization_alias="transform")
    variable: str | None = Field(None, alias="variable", serialization_alias="variable")

class StructureMapGroupRuleTargetParameter(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_date: str | None = Field(None, alias="valueDate", serialization_alias="valueDate")
    value_date_time: str | None = Field(None, alias="valueDateTime", serialization_alias="valueDateTime")
    value_decimal: float | None = Field(None, alias="valueDecimal", serialization_alias="valueDecimal")
    value_id: str | None = Field(None, alias="valueId", serialization_alias="valueId")
    value_integer: int | None = Field(None, alias="valueInteger", serialization_alias="valueInteger")
    value_string: str | None = Field(None, alias="valueString", serialization_alias="valueString")
    value_time: str | None = Field(None, alias="valueTime", serialization_alias="valueTime")

class StructureMapStructure(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    alias: str | None = Field(None, alias="alias", serialization_alias="alias")
    documentation: str | None = Field(None, alias="documentation", serialization_alias="documentation")
    mode: Literal["source", "queried", "target", "produced"] = Field(alias="mode", serialization_alias="mode")
    url: str = Field(alias="url", serialization_alias="url")


class StructureMap(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='StructureMap',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='StructureMap'
    )
    
    const: PyList[StructureMapConst] | None = Field(None, alias="const", serialization_alias="const")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    group: PyList[StructureMapGroup] = Field(alias="group", serialization_alias="group")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    import_: PyList[str] | None = Field(None, alias="import", serialization_alias="import")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    name: str = Field(alias="name", serialization_alias="name")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    structure: PyList[StructureMapStructure] | None = Field(None, alias="structure", serialization_alias="structure")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    url: str = Field(alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> StructureMap:
        return cls.model_validate_json(json)

