# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Coding, ContactDetail, Identifier, Period, UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class SubscriptionTopicTrigger(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    can_filter_by: PyList[SubscriptionTopicTriggerCanFilterBy] | None = Field(None, alias="canFilterBy", serialization_alias="canFilterBy")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    event: CodeableConcept | None = Field(None, alias="event", serialization_alias="event")
    fhir_path_criteria: str | None = Field(None, alias="fhirPathCriteria", serialization_alias="fhirPathCriteria")
    notification_shape: PyList[SubscriptionTopicTriggerNotificationShape] | None = Field(None, alias="notificationShape", serialization_alias="notificationShape")
    query_criteria: SubscriptionTopicTriggerQueryCriteria | None = Field(None, alias="queryCriteria", serialization_alias="queryCriteria")
    resource: str = Field(alias="resource", serialization_alias="resource")
    supported_interaction: PyList[Literal["create", "update", "delete"]] | None = Field(None, alias="supportedInteraction", serialization_alias="supportedInteraction")

class SubscriptionTopicTriggerCanFilterBy(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    comparator: PyList[Literal["eq", "ne", "gt", "lt", "ge", "le", "sa", "eb", "ap"]] | None = Field(None, alias="comparator", serialization_alias="comparator")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    filter_definition: str | None = Field(None, alias="filterDefinition", serialization_alias="filterDefinition")
    filter_parameter: str = Field(alias="filterParameter", serialization_alias="filterParameter")
    modifier: PyList[Literal["missing", "exact", "contains", "not", "text", "in", "not-in", "below", "above", "type", "identifier", "of-type", "code-text", "text-advanced", "iterate"]] | None = Field(None, alias="modifier", serialization_alias="modifier")
    resource: str | None = Field(None, alias="resource", serialization_alias="resource")

class SubscriptionTopicTriggerNotificationShape(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    include: PyList[str] | None = Field(None, alias="include", serialization_alias="include")
    related_query: PyList[SubscriptionTopicTriggerNotificationShapeRelatedQuery] | None = Field(None, alias="relatedQuery", serialization_alias="relatedQuery")
    resource: str = Field(alias="resource", serialization_alias="resource")
    rev_include: PyList[str] | None = Field(None, alias="revInclude", serialization_alias="revInclude")

class SubscriptionTopicTriggerNotificationShapeRelatedQuery(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    query: str = Field(alias="query", serialization_alias="query")
    query_type: Coding | None = Field(None, alias="queryType", serialization_alias="queryType")

class SubscriptionTopicTriggerQueryCriteria(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    current: str | None = Field(None, alias="current", serialization_alias="current")
    previous: str | None = Field(None, alias="previous", serialization_alias="previous")
    require_both: bool | None = Field(None, alias="requireBoth", serialization_alias="requireBoth")
    result_for_create: Literal["test-passes", "test-fails"] | None = Field(None, alias="resultForCreate", serialization_alias="resultForCreate")
    result_for_delete: Literal["test-passes", "test-fails"] | None = Field(None, alias="resultForDelete", serialization_alias="resultForDelete")


class SubscriptionTopic(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='SubscriptionTopic',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='SubscriptionTopic'
    )
    
    approval_date: str | None = Field(None, alias="approvalDate", serialization_alias="approvalDate")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    derived_from: PyList[str] | None = Field(None, alias="derivedFrom", serialization_alias="derivedFrom")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    effective_period: Period | None = Field(None, alias="effectivePeriod", serialization_alias="effectivePeriod")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    last_review_date: str | None = Field(None, alias="lastReviewDate", serialization_alias="lastReviewDate")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    trigger: PyList[SubscriptionTopicTrigger] | None = Field(None, alias="trigger", serialization_alias="trigger")
    url: str = Field(alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> SubscriptionTopic:
        return cls.model_validate_json(json)

