# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import BackboneElement, CodeableConcept, Coding, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class SubscriptionStatusNotificationEvent(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    additional_context: PyList[Reference] | None = Field(None, alias="additionalContext", serialization_alias="additionalContext")
    event_number: int = Field(alias="eventNumber", serialization_alias="eventNumber")
    focus: Reference | None = Field(None, alias="focus", serialization_alias="focus")
    related_query: PyList[SubscriptionStatusNotificationEventRelatedQuery] | None = Field(None, alias="relatedQuery", serialization_alias="relatedQuery")
    timestamp: str | None = Field(None, alias="timestamp", serialization_alias="timestamp")
    trigger_event: PyList[CodeableConcept] | None = Field(None, alias="triggerEvent", serialization_alias="triggerEvent")

class SubscriptionStatusNotificationEventRelatedQuery(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    query: str = Field(alias="query", serialization_alias="query")
    query_type: Coding | None = Field(None, alias="queryType", serialization_alias="queryType")


class SubscriptionStatus(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='SubscriptionStatus',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='SubscriptionStatus'
    )
    
    error: PyList[CodeableConcept] | None = Field(None, alias="error", serialization_alias="error")
    events_since_subscription_start: int | None = Field(None, alias="eventsSinceSubscriptionStart", serialization_alias="eventsSinceSubscriptionStart")
    notification_event: PyList[SubscriptionStatusNotificationEvent] | None = Field(None, alias="notificationEvent", serialization_alias="notificationEvent")
    status: Literal["requested", "active", "error", "off", "entered-in-error"] | None = Field(None, alias="status", serialization_alias="status")
    subscription: Reference = Field(alias="subscription", serialization_alias="subscription")
    topic: str | None = Field(None, alias="topic", serialization_alias="topic")
    type: Literal["handshake", "heartbeat", "event-notification", "query-status", "query-event"] = Field(alias="type", serialization_alias="type")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> SubscriptionStatus:
        return cls.model_validate_json(json)

