# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Annotation, Attachment, BackboneElement, CodeableConcept, Identifier, Quantity, Ratio, Reference
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class SubstanceDefinitionCharacterization(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    description: str | None = Field(None, alias="description", serialization_alias="description")
    file: PyList[Attachment] | None = Field(None, alias="file", serialization_alias="file")
    form: CodeableConcept | None = Field(None, alias="form", serialization_alias="form")
    technique: CodeableConcept | None = Field(None, alias="technique", serialization_alias="technique")

class SubstanceDefinitionCode(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    code: CodeableConcept | None = Field(None, alias="code", serialization_alias="code")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    source: PyList[Reference] | None = Field(None, alias="source", serialization_alias="source")
    status: CodeableConcept | None = Field(None, alias="status", serialization_alias="status")
    status_date: str | None = Field(None, alias="statusDate", serialization_alias="statusDate")

class SubstanceDefinitionMoiety(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    amount_quantity: Quantity | None = Field(None, alias="amountQuantity", serialization_alias="amountQuantity")
    amount_string: str | None = Field(None, alias="amountString", serialization_alias="amountString")
    identifier: Identifier | None = Field(None, alias="identifier", serialization_alias="identifier")
    measurement_type: CodeableConcept | None = Field(None, alias="measurementType", serialization_alias="measurementType")
    molecular_formula: str | None = Field(None, alias="molecularFormula", serialization_alias="molecularFormula")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    optical_activity: CodeableConcept | None = Field(None, alias="opticalActivity", serialization_alias="opticalActivity")
    role: CodeableConcept | None = Field(None, alias="role", serialization_alias="role")
    stereochemistry: CodeableConcept | None = Field(None, alias="stereochemistry", serialization_alias="stereochemistry")

class SubstanceDefinitionMolecularWeight(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    amount: Quantity = Field(alias="amount", serialization_alias="amount")
    method: CodeableConcept | None = Field(None, alias="method", serialization_alias="method")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class SubstanceDefinitionName(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    domain: PyList[CodeableConcept] | None = Field(None, alias="domain", serialization_alias="domain")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    language: PyList[CodeableConcept] | None = Field(None, alias="language", serialization_alias="language")
    name: str = Field(alias="name", serialization_alias="name")
    official: PyList[SubstanceDefinitionNameOfficial] | None = Field(None, alias="official", serialization_alias="official")
    preferred: bool | None = Field(None, alias="preferred", serialization_alias="preferred")
    source: PyList[Reference] | None = Field(None, alias="source", serialization_alias="source")
    status: CodeableConcept | None = Field(None, alias="status", serialization_alias="status")
    synonym: PyList[SubstanceDefinitionName] | None = Field(None, alias="synonym", serialization_alias="synonym")
    translation: PyList[SubstanceDefinitionName] | None = Field(None, alias="translation", serialization_alias="translation")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class SubstanceDefinitionNameOfficial(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    authority: CodeableConcept | None = Field(None, alias="authority", serialization_alias="authority")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    status: CodeableConcept | None = Field(None, alias="status", serialization_alias="status")

class SubstanceDefinitionProperty(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    type: CodeableConcept = Field(alias="type", serialization_alias="type")
    value_attachment: Attachment | None = Field(None, alias="valueAttachment", serialization_alias="valueAttachment")
    value_boolean: bool | None = Field(None, alias="valueBoolean", serialization_alias="valueBoolean")
    value_codeable_concept: CodeableConcept | None = Field(None, alias="valueCodeableConcept", serialization_alias="valueCodeableConcept")
    value_date: str | None = Field(None, alias="valueDate", serialization_alias="valueDate")
    value_quantity: Quantity | None = Field(None, alias="valueQuantity", serialization_alias="valueQuantity")

class SubstanceDefinitionRelationship(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    amount_quantity: Quantity | None = Field(None, alias="amountQuantity", serialization_alias="amountQuantity")
    amount_ratio: Ratio | None = Field(None, alias="amountRatio", serialization_alias="amountRatio")
    amount_string: str | None = Field(None, alias="amountString", serialization_alias="amountString")
    comparator: CodeableConcept | None = Field(None, alias="comparator", serialization_alias="comparator")
    is_defining: bool | None = Field(None, alias="isDefining", serialization_alias="isDefining")
    ratio_high_limit_amount: Ratio | None = Field(None, alias="ratioHighLimitAmount", serialization_alias="ratioHighLimitAmount")
    source: PyList[Reference] | None = Field(None, alias="source", serialization_alias="source")
    substance_definition_codeable_concept: CodeableConcept | None = Field(None, alias="substanceDefinitionCodeableConcept", serialization_alias="substanceDefinitionCodeableConcept")
    substance_definition_reference: Reference | None = Field(None, alias="substanceDefinitionReference", serialization_alias="substanceDefinitionReference")
    type: CodeableConcept = Field(alias="type", serialization_alias="type")

class SubstanceDefinitionSourceMaterial(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    country_of_origin: PyList[CodeableConcept] | None = Field(None, alias="countryOfOrigin", serialization_alias="countryOfOrigin")
    genus: CodeableConcept | None = Field(None, alias="genus", serialization_alias="genus")
    part: CodeableConcept | None = Field(None, alias="part", serialization_alias="part")
    species: CodeableConcept | None = Field(None, alias="species", serialization_alias="species")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")

class SubstanceDefinitionStructure(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    molecular_formula: str | None = Field(None, alias="molecularFormula", serialization_alias="molecularFormula")
    molecular_formula_by_moiety: str | None = Field(None, alias="molecularFormulaByMoiety", serialization_alias="molecularFormulaByMoiety")
    molecular_weight: SubstanceDefinitionMolecularWeight | None = Field(None, alias="molecularWeight", serialization_alias="molecularWeight")
    optical_activity: CodeableConcept | None = Field(None, alias="opticalActivity", serialization_alias="opticalActivity")
    representation: PyList[SubstanceDefinitionStructureRepresentation] | None = Field(None, alias="representation", serialization_alias="representation")
    source_document: PyList[Reference] | None = Field(None, alias="sourceDocument", serialization_alias="sourceDocument")
    stereochemistry: CodeableConcept | None = Field(None, alias="stereochemistry", serialization_alias="stereochemistry")
    technique: PyList[CodeableConcept] | None = Field(None, alias="technique", serialization_alias="technique")

class SubstanceDefinitionStructureRepresentation(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    document: Reference | None = Field(None, alias="document", serialization_alias="document")
    format: CodeableConcept | None = Field(None, alias="format", serialization_alias="format")
    representation: str | None = Field(None, alias="representation", serialization_alias="representation")
    type: CodeableConcept | None = Field(None, alias="type", serialization_alias="type")


class SubstanceDefinition(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='SubstanceDefinition',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='SubstanceDefinition'
    )
    
    characterization: PyList[SubstanceDefinitionCharacterization] | None = Field(None, alias="characterization", serialization_alias="characterization")
    classification: PyList[CodeableConcept] | None = Field(None, alias="classification", serialization_alias="classification")
    code: PyList[SubstanceDefinitionCode] | None = Field(None, alias="code", serialization_alias="code")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    domain: CodeableConcept | None = Field(None, alias="domain", serialization_alias="domain")
    grade: PyList[CodeableConcept] | None = Field(None, alias="grade", serialization_alias="grade")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    information_source: PyList[Reference] | None = Field(None, alias="informationSource", serialization_alias="informationSource")
    manufacturer: PyList[Reference] | None = Field(None, alias="manufacturer", serialization_alias="manufacturer")
    moiety: PyList[SubstanceDefinitionMoiety] | None = Field(None, alias="moiety", serialization_alias="moiety")
    molecular_weight: PyList[SubstanceDefinitionMolecularWeight] | None = Field(None, alias="molecularWeight", serialization_alias="molecularWeight")
    name: PyList[SubstanceDefinitionName] | None = Field(None, alias="name", serialization_alias="name")
    note: PyList[Annotation] | None = Field(None, alias="note", serialization_alias="note")
    nucleic_acid: Reference | None = Field(None, alias="nucleicAcid", serialization_alias="nucleicAcid")
    polymer: Reference | None = Field(None, alias="polymer", serialization_alias="polymer")
    property: PyList[SubstanceDefinitionProperty] | None = Field(None, alias="property", serialization_alias="property")
    protein: Reference | None = Field(None, alias="protein", serialization_alias="protein")
    reference_information: Reference | None = Field(None, alias="referenceInformation", serialization_alias="referenceInformation")
    relationship: PyList[SubstanceDefinitionRelationship] | None = Field(None, alias="relationship", serialization_alias="relationship")
    source_material: SubstanceDefinitionSourceMaterial | None = Field(None, alias="sourceMaterial", serialization_alias="sourceMaterial")
    status: CodeableConcept | None = Field(None, alias="status", serialization_alias="status")
    structure: SubstanceDefinitionStructure | None = Field(None, alias="structure", serialization_alias="structure")
    supplier: PyList[Reference] | None = Field(None, alias="supplier", serialization_alias="supplier")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> SubstanceDefinition:
        return cls.model_validate_json(json)

