# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import Attachment, BackboneElement, Identifier, Period
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class TestReportParameter(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    documentation: str | None = Field(None, alias="documentation", serialization_alias="documentation")
    name: str = Field(alias="name", serialization_alias="name")

class TestReportParticipant(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    display: str | None = Field(None, alias="display", serialization_alias="display")
    type: Literal["test-engine", "client", "server"] = Field(alias="type", serialization_alias="type")
    uri: str | None = Field(None, alias="uri", serialization_alias="uri")
    version: str | None = Field(None, alias="version", serialization_alias="version")

class TestReportSetup(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: PyList[TestReportSetupAction] = Field(alias="action", serialization_alias="action")

class TestReportSetupAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    assert_: TestReportSetupActionAssert | None = Field(None, alias="assert", serialization_alias="assert")
    operation: TestReportSetupActionOperation | None = Field(None, alias="operation", serialization_alias="operation")

class TestReportSetupActionAssert(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    detail: str | None = Field(None, alias="detail", serialization_alias="detail")
    message: str | None = Field(None, alias="message", serialization_alias="message")
    requirement: PyList[TestReportSetupActionAssertRequirement] | None = Field(None, alias="requirement", serialization_alias="requirement")
    result: Literal["pass", "skip", "fail", "warning", "error"] = Field(alias="result", serialization_alias="result")

class TestReportSetupActionAssertRequirement(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    link_canonical: str | None = Field(None, alias="linkCanonical", serialization_alias="linkCanonical")
    link_uri: str | None = Field(None, alias="linkUri", serialization_alias="linkUri")

class TestReportSetupActionOperation(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    detail: str | None = Field(None, alias="detail", serialization_alias="detail")
    message: str | None = Field(None, alias="message", serialization_alias="message")
    result: Literal["pass", "skip", "fail", "warning", "error"] = Field(alias="result", serialization_alias="result")

class TestReportTeardown(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: PyList[TestReportTeardownAction] = Field(alias="action", serialization_alias="action")

class TestReportTeardownAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    operation: TestReportSetupActionOperation = Field(alias="operation", serialization_alias="operation")

class TestReportTest(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: PyList[TestReportTestAction] = Field(alias="action", serialization_alias="action")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    log: Attachment | None = Field(None, alias="log", serialization_alias="log")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    period: Period | None = Field(None, alias="period", serialization_alias="period")
    result: Literal["pass", "skip", "fail", "warning", "error"] | None = Field(None, alias="result", serialization_alias="result")

class TestReportTestAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    assert_: TestReportSetupActionAssert | None = Field(None, alias="assert", serialization_alias="assert")
    operation: TestReportSetupActionOperation | None = Field(None, alias="operation", serialization_alias="operation")


class TestReport(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='TestReport',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='TestReport'
    )
    
    identifier: Identifier | None = Field(None, alias="identifier", serialization_alias="identifier")
    issued: str | None = Field(None, alias="issued", serialization_alias="issued")
    log: Attachment | None = Field(None, alias="log", serialization_alias="log")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    parameter: PyList[TestReportParameter] | None = Field(None, alias="parameter", serialization_alias="parameter")
    participant: PyList[TestReportParticipant] | None = Field(None, alias="participant", serialization_alias="participant")
    presented_form: Attachment | None = Field(None, alias="presentedForm", serialization_alias="presentedForm")
    result: Literal["pass", "fail", "pending"] = Field(alias="result", serialization_alias="result")
    score: float | None = Field(None, alias="score", serialization_alias="score")
    setup: TestReportSetup | None = Field(None, alias="setup", serialization_alias="setup")
    status: Literal["completed", "in-progress", "waiting", "stopped", "entered-in-error"] = Field(alias="status", serialization_alias="status")
    teardown: TestReportTeardown | None = Field(None, alias="teardown", serialization_alias="teardown")
    test: PyList[TestReportTest] | None = Field(None, alias="test", serialization_alias="test")
    tester: str | None = Field(None, alias="tester", serialization_alias="tester")
    test_script: str = Field(alias="testScript", serialization_alias="testScript")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> TestReport:
        return cls.model_validate_json(json)

