# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    Attachment, BackboneElement, CodeableConcept, CodeableReference, Coding, ContactDetail, Identifier, Reference, \
    UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class TestPlanDependency(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    description: str | None = Field(None, alias="description", serialization_alias="description")
    predecessor: Reference | None = Field(None, alias="predecessor", serialization_alias="predecessor")

class TestPlanScope(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    artifact_canonical: str | None = Field(None, alias="artifactCanonical", serialization_alias="artifactCanonical")
    artifact_markdown: str | None = Field(None, alias="artifactMarkdown", serialization_alias="artifactMarkdown")
    artifact_uri: str | None = Field(None, alias="artifactUri", serialization_alias="artifactUri")

class TestPlanTestCase(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    assertion: PyList[TestPlanTestCaseAssertion] | None = Field(None, alias="assertion", serialization_alias="assertion")
    dependency: PyList[TestPlanTestCaseDependency] | None = Field(None, alias="dependency", serialization_alias="dependency")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    key: str = Field(alias="key", serialization_alias="key")
    requirement: PyList[TestPlanTestCaseRequirement] | None = Field(None, alias="requirement", serialization_alias="requirement")
    scope: PyList[TestPlanTestCaseScope] | None = Field(None, alias="scope", serialization_alias="scope")
    sequence: int | None = Field(None, alias="sequence", serialization_alias="sequence")
    test_case: PyList[TestPlanTestCase] | None = Field(None, alias="testCase", serialization_alias="testCase")
    test_data: PyList[TestPlanTestCaseTestData] | None = Field(None, alias="testData", serialization_alias="testData")
    test_run: PyList[TestPlanTestCaseTestRun] | None = Field(None, alias="testRun", serialization_alias="testRun")

class TestPlanTestCaseAssertion(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    object: PyList[CodeableReference] | None = Field(None, alias="object", serialization_alias="object")
    result: PyList[CodeableReference] | None = Field(None, alias="result", serialization_alias="result")
    type: PyList[CodeableConcept] | None = Field(None, alias="type", serialization_alias="type")

class TestPlanTestCaseDependency(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    description: str | None = Field(None, alias="description", serialization_alias="description")
    key: str | None = Field(None, alias="key", serialization_alias="key")
    reference: str | None = Field(None, alias="reference", serialization_alias="reference")

class TestPlanTestCaseRequirement(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    key: str = Field(alias="key", serialization_alias="key")
    reference: str = Field(alias="reference", serialization_alias="reference")

class TestPlanTestCaseScope(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    artifact_canonical: str | None = Field(None, alias="artifactCanonical", serialization_alias="artifactCanonical")
    artifact_markdown: str | None = Field(None, alias="artifactMarkdown", serialization_alias="artifactMarkdown")
    artifact_uri: str | None = Field(None, alias="artifactUri", serialization_alias="artifactUri")

class TestPlanTestCaseTestData(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    content: Reference | None = Field(None, alias="content", serialization_alias="content")
    source_reference: Reference | None = Field(None, alias="sourceReference", serialization_alias="sourceReference")
    source_string: str | None = Field(None, alias="sourceString", serialization_alias="sourceString")
    source_uri: str | None = Field(None, alias="sourceUri", serialization_alias="sourceUri")
    type: Coding = Field(alias="type", serialization_alias="type")

class TestPlanTestCaseTestRun(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    narrative: str | None = Field(None, alias="narrative", serialization_alias="narrative")
    script: TestPlanTestCaseTestRunScript | None = Field(None, alias="script", serialization_alias="script")

class TestPlanTestCaseTestRunScript(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    language: CodeableConcept | None = Field(None, alias="language", serialization_alias="language")
    source_attachment: Attachment | None = Field(None, alias="sourceAttachment", serialization_alias="sourceAttachment")
    source_reference: Reference | None = Field(None, alias="sourceReference", serialization_alias="sourceReference")
    source_string: str | None = Field(None, alias="sourceString", serialization_alias="sourceString")


class TestPlan(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='TestPlan',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='TestPlan'
    )
    
    category: PyList[CodeableConcept] | None = Field(None, alias="category", serialization_alias="category")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    dependency: PyList[TestPlanDependency] | None = Field(None, alias="dependency", serialization_alias="dependency")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    exit_criteria: str | None = Field(None, alias="exitCriteria", serialization_alias="exitCriteria")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    scope: PyList[TestPlanScope] | None = Field(None, alias="scope", serialization_alias="scope")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    test_case: PyList[TestPlanTestCase] | None = Field(None, alias="testCase", serialization_alias="testCase")
    test_tools: str | None = Field(None, alias="testTools", serialization_alias="testTools")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> TestPlan:
        return cls.model_validate_json(json)

