# WARNING: This file is autogenerated by FHIR Schema Codegen.
# https://github.com/fhir-schema/fhir-schema-codegen
# Any manual changes made to this file may be overwritten.

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field, PositiveInt
from typing import List as PyList, Literal

from fhirsdk.hl7_fhir_r6_core.base import \
    BackboneElement, CodeableConcept, Coding, ContactDetail, Identifier, Reference, UsageContext
from fhirsdk.hl7_fhir_r6_core.domain_resource import DomainResource
from fhirsdk.hl7_fhir_r6_core.resource_families import DomainResourceFamily


class TestScriptCommon(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: PyList[TestScriptCommonAction] = Field(alias="action", serialization_alias="action")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    key: str = Field(alias="key", serialization_alias="key")
    name: str | None = Field(None, alias="name", serialization_alias="name")
    parameter: PyList[TestScriptCommonParameter] | None = Field(None, alias="parameter", serialization_alias="parameter")

class TestScriptCommonAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    assert_: TestScriptSetupActionAssert | None = Field(None, alias="assert", serialization_alias="assert")
    operation: TestScriptSetupActionOperation | None = Field(None, alias="operation", serialization_alias="operation")

class TestScriptCommonParameter(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    description: str | None = Field(None, alias="description", serialization_alias="description")
    name: str | None = Field(None, alias="name", serialization_alias="name")

class TestScriptFixture(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    autocreate: bool = Field(alias="autocreate", serialization_alias="autocreate")
    autodelete: bool = Field(alias="autodelete", serialization_alias="autodelete")
    resource: Reference | None = Field(None, alias="resource", serialization_alias="resource")

class TestScriptMetadata(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    capability: PyList[TestScriptMetadataCapability] = Field(alias="capability", serialization_alias="capability")
    link: PyList[TestScriptMetadataLink] | None = Field(None, alias="link", serialization_alias="link")

class TestScriptMetadataCapability(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    capabilities: str = Field(alias="capabilities", serialization_alias="capabilities")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    destination: int | None = Field(None, alias="destination", serialization_alias="destination")
    link: PyList[str] | None = Field(None, alias="link", serialization_alias="link")
    origin: PyList[int] | None = Field(None, alias="origin", serialization_alias="origin")
    required: bool = Field(alias="required", serialization_alias="required")
    validated: bool = Field(alias="validated", serialization_alias="validated")

class TestScriptMetadataLink(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    description: str | None = Field(None, alias="description", serialization_alias="description")
    url: str = Field(alias="url", serialization_alias="url")

class TestScriptScope(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    artifact: str = Field(alias="artifact", serialization_alias="artifact")
    conformance: CodeableConcept | None = Field(None, alias="conformance", serialization_alias="conformance")
    phase: CodeableConcept | None = Field(None, alias="phase", serialization_alias="phase")

class TestScriptSetup(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: PyList[TestScriptSetupAction] | None = Field(None, alias="action", serialization_alias="action")

class TestScriptSetupAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    assert_: TestScriptSetupActionAssert | None = Field(None, alias="assert", serialization_alias="assert")
    common: TestScriptSetupActionCommon | None = Field(None, alias="common", serialization_alias="common")
    operation: TestScriptSetupActionOperation | None = Field(None, alias="operation", serialization_alias="operation")

class TestScriptSetupActionAssert(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    compare_to_source_expression: str | None = Field(None, alias="compareToSourceExpression", serialization_alias="compareToSourceExpression")
    compare_to_source_id: str | None = Field(None, alias="compareToSourceId", serialization_alias="compareToSourceId")
    compare_to_source_path: str | None = Field(None, alias="compareToSourcePath", serialization_alias="compareToSourcePath")
    content_type: str | None = Field(None, alias="contentType", serialization_alias="contentType")
    default_manual_completion: Literal["fail", "pass", "skip", "stop"] | None = Field(None, alias="defaultManualCompletion", serialization_alias="defaultManualCompletion")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    direction: Literal["response", "request"] | None = Field(None, alias="direction", serialization_alias="direction")
    expression: str | None = Field(None, alias="expression", serialization_alias="expression")
    header_field: str | None = Field(None, alias="headerField", serialization_alias="headerField")
    label: str | None = Field(None, alias="label", serialization_alias="label")
    minimum_id: str | None = Field(None, alias="minimumId", serialization_alias="minimumId")
    navigation_links: bool | None = Field(None, alias="navigationLinks", serialization_alias="navigationLinks")
    operator: Literal["equals", "notEquals", "in", "notIn", "greaterThan", "lessThan", "empty", "notEmpty", "contains", "notContains", "eval", "manualEval"] | None = Field(None, alias="operator", serialization_alias="operator")
    path: str | None = Field(None, alias="path", serialization_alias="path")
    request_method: Literal["delete", "get", "options", "patch", "post", "put", "head"] | None = Field(None, alias="requestMethod", serialization_alias="requestMethod")
    request_url: str | None = Field(None, alias="requestURL", serialization_alias="requestURL")
    requirement: PyList[TestScriptSetupActionAssertRequirement] | None = Field(None, alias="requirement", serialization_alias="requirement")
    resource: str | None = Field(None, alias="resource", serialization_alias="resource")
    response: Literal["continue", "switchingProtocols", "okay", "created", "accepted", "nonAuthoritativeInformation", "noContent", "resetContent", "partialContent", "multipleChoices", "movedPermanently", "found", "seeOther", "notModified", "useProxy", "temporaryRedirect", "permanentRedirect", "badRequest", "unauthorized", "paymentRequired", "forbidden", "notFound", "methodNotAllowed", "notAcceptable", "proxyAuthenticationRequired", "requestTimeout", "conflict", "gone", "lengthRequired", "preconditionFailed", "contentTooLarge", "uriTooLong", "unsupportedMediaType", "rangeNotSatisfiable", "expectationFailed", "misdirectedRequest", "unprocessableContent", "upgradeRequired", "internalServerError", "notImplemented", "badGateway", "serviceUnavailable", "gatewayTimeout", "httpVersionNotSupported"] | None = Field(None, alias="response", serialization_alias="response")
    response_code: str | None = Field(None, alias="responseCode", serialization_alias="responseCode")
    source_id: str | None = Field(None, alias="sourceId", serialization_alias="sourceId")
    stop_test_on_fail: bool = Field(alias="stopTestOnFail", serialization_alias="stopTestOnFail")
    validate_profile_id: str | None = Field(None, alias="validateProfileId", serialization_alias="validateProfileId")
    value: str | None = Field(None, alias="value", serialization_alias="value")
    warning_only: bool = Field(alias="warningOnly", serialization_alias="warningOnly")

class TestScriptSetupActionAssertRequirement(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    key: str = Field(alias="key", serialization_alias="key")
    reference: str = Field(alias="reference", serialization_alias="reference")

class TestScriptSetupActionCommon(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    key_ref: str = Field(alias="keyRef", serialization_alias="keyRef")
    parameter: PyList[TestScriptSetupActionCommonParameter] | None = Field(None, alias="parameter", serialization_alias="parameter")
    test_script: str | None = Field(None, alias="testScript", serialization_alias="testScript")

class TestScriptSetupActionCommonParameter(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    name: str = Field(alias="name", serialization_alias="name")
    value: str = Field(alias="value", serialization_alias="value")

class TestScriptSetupActionOperation(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    accept: str | None = Field(None, alias="accept", serialization_alias="accept")
    content_type: str | None = Field(None, alias="contentType", serialization_alias="contentType")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    destination: int | None = Field(None, alias="destination", serialization_alias="destination")
    encode_request_url: bool = Field(alias="encodeRequestUrl", serialization_alias="encodeRequestUrl")
    label: str | None = Field(None, alias="label", serialization_alias="label")
    method: Literal["delete", "get", "options", "patch", "post", "put", "head"] | None = Field(None, alias="method", serialization_alias="method")
    origin: int | None = Field(None, alias="origin", serialization_alias="origin")
    params: str | None = Field(None, alias="params", serialization_alias="params")
    request_header: PyList[TestScriptSetupActionOperationRequestHeader] | None = Field(None, alias="requestHeader", serialization_alias="requestHeader")
    request_id: str | None = Field(None, alias="requestId", serialization_alias="requestId")
    resource: str | None = Field(None, alias="resource", serialization_alias="resource")
    response_id: str | None = Field(None, alias="responseId", serialization_alias="responseId")
    source_id: str | None = Field(None, alias="sourceId", serialization_alias="sourceId")
    target_id: str | None = Field(None, alias="targetId", serialization_alias="targetId")
    type: Coding | None = Field(None, alias="type", serialization_alias="type")
    url: str | None = Field(None, alias="url", serialization_alias="url")

class TestScriptSetupActionOperationRequestHeader(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    field: str = Field(alias="field", serialization_alias="field")
    value: str = Field(alias="value", serialization_alias="value")

class TestScriptTeardown(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: PyList[TestScriptTeardownAction] = Field(alias="action", serialization_alias="action")

class TestScriptTeardownAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    common: TestScriptSetupActionCommon | None = Field(None, alias="common", serialization_alias="common")
    operation: TestScriptSetupActionOperation = Field(alias="operation", serialization_alias="operation")

class TestScriptTest(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    action: PyList[TestScriptTestAction] | None = Field(None, alias="action", serialization_alias="action")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    name: str | None = Field(None, alias="name", serialization_alias="name")

class TestScriptTestAction(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    assert_: TestScriptSetupActionAssert | None = Field(None, alias="assert", serialization_alias="assert")
    common: TestScriptSetupActionCommon | None = Field(None, alias="common", serialization_alias="common")
    operation: TestScriptSetupActionOperation | None = Field(None, alias="operation", serialization_alias="operation")

class TestScriptTestSystem(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    actor: PyList[str] | None = Field(None, alias="actor", serialization_alias="actor")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    index: PositiveInt = Field(alias="index", serialization_alias="index")
    title: str = Field(alias="title", serialization_alias="title")
    url: str | None = Field(None, alias="url", serialization_alias="url")

class TestScriptVariable(BackboneElement):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    default_value: str | None = Field(None, alias="defaultValue", serialization_alias="defaultValue")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    expression: str | None = Field(None, alias="expression", serialization_alias="expression")
    header_field: str | None = Field(None, alias="headerField", serialization_alias="headerField")
    hint: str | None = Field(None, alias="hint", serialization_alias="hint")
    name: str = Field(alias="name", serialization_alias="name")
    path: str | None = Field(None, alias="path", serialization_alias="path")
    source_id: str | None = Field(None, alias="sourceId", serialization_alias="sourceId")


class TestScript(DomainResource):
    model_config = ConfigDict(validate_by_name=True, serialize_by_alias=True, extra="forbid")
    
    resource_type: str = Field(
        default='TestScript',
        alias='resourceType',
        serialization_alias='resourceType',
        frozen=True,
        pattern='TestScript'
    )
    
    common: PyList[TestScriptCommon] | None = Field(None, alias="common", serialization_alias="common")
    contact: PyList[ContactDetail] | None = Field(None, alias="contact", serialization_alias="contact")
    copyright: str | None = Field(None, alias="copyright", serialization_alias="copyright")
    copyright_label: str | None = Field(None, alias="copyrightLabel", serialization_alias="copyrightLabel")
    date: str | None = Field(None, alias="date", serialization_alias="date")
    description: str | None = Field(None, alias="description", serialization_alias="description")
    experimental: bool | None = Field(None, alias="experimental", serialization_alias="experimental")
    fixture: PyList[TestScriptFixture] | None = Field(None, alias="fixture", serialization_alias="fixture")
    identifier: PyList[Identifier] | None = Field(None, alias="identifier", serialization_alias="identifier")
    jurisdiction: PyList[CodeableConcept] | None = Field(None, alias="jurisdiction", serialization_alias="jurisdiction")
    metadata: TestScriptMetadata | None = Field(None, alias="metadata", serialization_alias="metadata")
    name: str = Field(alias="name", serialization_alias="name")
    profile: PyList[str] | None = Field(None, alias="profile", serialization_alias="profile")
    publisher: str | None = Field(None, alias="publisher", serialization_alias="publisher")
    purpose: str | None = Field(None, alias="purpose", serialization_alias="purpose")
    scope: PyList[TestScriptScope] | None = Field(None, alias="scope", serialization_alias="scope")
    setup: TestScriptSetup | None = Field(None, alias="setup", serialization_alias="setup")
    status: Literal["draft", "active", "retired", "unknown"] = Field(alias="status", serialization_alias="status")
    teardown: TestScriptTeardown | None = Field(None, alias="teardown", serialization_alias="teardown")
    test: PyList[TestScriptTest] | None = Field(None, alias="test", serialization_alias="test")
    test_system: PyList[TestScriptTestSystem] | None = Field(None, alias="testSystem", serialization_alias="testSystem")
    title: str | None = Field(None, alias="title", serialization_alias="title")
    url: str | None = Field(None, alias="url", serialization_alias="url")
    use_context: PyList[UsageContext] | None = Field(None, alias="useContext", serialization_alias="useContext")
    variable: PyList[TestScriptVariable] | None = Field(None, alias="variable", serialization_alias="variable")
    version: str | None = Field(None, alias="version", serialization_alias="version")
    version_algorithm_coding: Coding | None = Field(None, alias="versionAlgorithmCoding", serialization_alias="versionAlgorithmCoding")
    version_algorithm_string: str | None = Field(None, alias="versionAlgorithmString", serialization_alias="versionAlgorithmString")
    
    def to_json(self, indent: int | None = None) -> str:
        return self.model_dump_json(exclude_unset=True, exclude_none=True, indent=indent)
    
    @classmethod
    def from_json(cls, json: str) -> TestScript:
        return cls.model_validate_json(json)

